--
-- PostgreSQL database dump
--

\restrict 3qIAl11L79Wc9JzeBlfpcBjyuSZqwrOUyaLZdarmYtEgageaMeHanwuPQ02XTZV

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2026-02-18 16:39:06

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16508)
-- Name: directors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.directors (
    id integer NOT NULL,
    name character varying(255) DEFAULT NULL::character varying,
    featured_names character varying(255) DEFAULT NULL::character varying
);


ALTER TABLE public.directors OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16516)
-- Name: directors_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.directors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.directors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16517)
-- Name: genres; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.genres (
    id integer NOT NULL,
    genre_name text
);


ALTER TABLE public.genres OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16523)
-- Name: genres_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.genres ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.genres_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16524)
-- Name: haswatched; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.haswatched (
    id integer NOT NULL,
    user_id integer,
    title_id integer,
    watch_date date NOT NULL,
    watch_count integer NOT NULL,
    user_comment text,
    user_rating numeric(3,1) DEFAULT NULL::numeric,
    series_id integer
);


ALTER TABLE public.haswatched OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16533)
-- Name: haswatched_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.haswatched ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.haswatched_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16534)
-- Name: series; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.series (
    id integer NOT NULL,
    series_name character varying(255) NOT NULL,
    creator character varying(255) NOT NULL,
    genre character varying(255) DEFAULT NULL::character varying,
    year_release smallint NOT NULL,
    seasons integer NOT NULL,
    episodes integer NOT NULL,
    season_ended character varying(10) NOT NULL,
    CONSTRAINT series_season_ended_check CHECK (((season_ended)::text = ANY (ARRAY[('YES'::character varying)::text, ('NO'::character varying)::text])))
);


ALTER TABLE public.series OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16548)
-- Name: series_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.series ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.series_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16549)
-- Name: titles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.titles (
    id integer NOT NULL,
    title character varying(255) NOT NULL,
    director_id integer NOT NULL,
    genre character varying(255) DEFAULT NULL::character varying,
    year_release smallint NOT NULL,
    synopsis text,
    category character varying(20) DEFAULT 'Movie'::character varying,
    runtime numeric(3,2),
    genres integer,
    CONSTRAINT titles_category_check CHECK (((category)::text = ANY (ARRAY[('Movie'::character varying)::text, ('Documentary'::character varying)::text, ('Animation'::character varying)::text])))
);


ALTER TABLE public.titles OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16561)
-- Name: titles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.titles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.titles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16562)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    user_name character varying(255) NOT NULL,
    email character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16570)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16571)
-- Name: watchlist; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.watchlist (
    id integer NOT NULL,
    title_id integer
);


ALTER TABLE public.watchlist OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16575)
-- Name: watchlist_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.watchlist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.watchlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5067 (class 0 OID 16508)
-- Dependencies: 219
-- Data for Name: directors; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.directors (id, name, featured_names) FROM stdin;
7	Eduardo Sánches	
8	Daniel Myrick	
11	Grégory Levasseur	
13	Abel Ferrara	
14	Tobe Hooper	
15	Ti West	
16		Jay Cheel, Jordan Downey, Christian Long, Justin Long, Justin Martinez, Virat Pal, Kate Siegel
17		Bryan M. Ferguson, Casper Kelly, R.H. Norman
18	Jude S. Walko	
19	\N	John Bruno/John Halas/Julian Harris
20	\N	Michael Coldewey/Michel Lemire
21	\N	Christian Nyby/Howard Hawks
22	\N	Banjong Pisanthanakun/Parkpoom Wongpoom
23	\N	David Amito/Michael Laicini
24	\N	Cristie Whiles/Fred Vogel/Jerami Cruise/Killjoy/Michael Todd Schneider
25	\N	Colin Minihan/Stuart Ortiz
26	\N	Karl Freund/Tod Browning
27	\N	Bryan Woods/Scott Beck
28	\N	Alberto Cavalcanti/Basil Dearden/Charles Crichton
29	\N	Danny Philippou/Michael Philippou
30	\N	Frank Oz/Jim Henson
31	\N	Danny Boyle/Loveleen Tandan
32	\N	Ethan Coen/Joel
33	\N	Lana/Lilly Wachowski
34	\N	Ethan Coen/Joel
35	\N	Fernando Meirelles/Kátia Lund
36	\N	Ethan Coen/Joel
37	\N	Aaron Moorhead/Justin Benson
38	\N	Michael/Peter Spierig
39	\N	Chris Caldwell/Zeek Earl
40	\N	Aaron Moorhead/Justin Benson
41	\N	Daniel Myrick/Eduardo Sánchez
42	\N	Alexandre Bustillo/Julien Maury
43	\N	Jaume Balagueró/Paco Plaza
44	\N	Anthony/Joe Russo
45	\N	Neveldine/Taylor
46	\N	Anthony/Joe Russo
47	\N	Anthony/Joe Russo
48	\N	Mario Bava/Riccardo Freda
49	\N	Edward Ludwig/Izvestiy Antonovich
50	\N	Freddie Francis/Steve Sekely
51	\N	Sidney Salkow/Ubaldo Ragona
52	\N	Jack Arnold/Joseph M. Newman
53	\N	Colin Strause/Greg Strause
82	Ishirô Honda	\N
83	Matthew Robbins	\N
84	Chuck Russell	\N
85	Randal Kleiser	\N
86	John Carpenter	\N
87	Stewart Raffill	\N
88	Alex Cox	\N
89	Jack Sholder	\N
90	Terry Gilliam	\N
91	Luc Besson	\N
92	Scott Derrickson	\N
93	Pete Travis	\N
94	Steven Soderbergh	\N
95	Greg Berlanti	\N
96	James Gray	\N
97	Kurt Wimmer	\N
98	Wes Ball	\N
99	Sam Esmail	\N
100	Francis Ford Coppola	\N
101	Robert Wise	\N
102	David Cronenberg	\N
103	Chris Walas	\N
104	Fred Olen Ray	\N
105	George Nolfi	\N
106	Drew Hancock	\N
107	Bryan Bertino	\N
108	Paul McGuigan	\N
109	Ari Aster	\N
110	Chris Nash	\N
111	Ishana Shyamalan	\N
112	Susanne Bier	\N
113	OZ Perkins	\N
114	Natalie Erika James	\N
115	Coralie Fargeat	\N
116	James Watkins	\N
117	Alexandre Aja	\N
118	David F. Sandberg	\N
119	David Robert Mitchell	\N
120	John Erick Dowdle	\N
121	Anthony Cousins	\N
122	Michael Goi	\N
123	Philip Kaufman	\N
124	Christian Tafdrup	\N
125	George Miller	\N
126	Willian Wayler	\N
127	Danny Cannon	\N
128	Fernando Barreda Luna	\N
129	Adrian Țofei	\N
130	Adam Robitel	\N
131	George A. Romero	\N
132	Bobby Roe	\N
133	Rob Savage	\N
134	Benjamin Barfoot	\N
135	Andy Milligan	\N
136	William Friedkin	\N
137	Peter Hyams	\N
138	Zoë Kravitz	\N
139	Kyle Mooney	\N
140	James Whale	\N
141	William Castle	\N
142	Robert Eggers	\N
143	Boris Sagal	\N
144	Dario Argento	\N
145	Luca Guadagnino	\N
146	Kevin Smith	\N
147	Kiyoshi Kurosawa	\N
148	Parker Finn	\N
149	Leigh Whannell	\N
150	George Waggner	\N
151	Zach LipovskyAdam B. Stein	\N
152	André De Toth	\N
153	Jacques Tourneur	\N
154	Adrian Lyne	\N
155	Clive Barker	\N
156	Zach Cregger	\N
157	Michael Chaves	\N
158	Mel Gibson	\N
159	Matthew Holmes	\N
160	Kelly Marcel	\N
161	Ridley Scott	\N
162	Joel Schumacher	\N
163	Kevin Macdonald	\N
164	J.C. Chandor	\N
165	Justin Routt	\N
166	Adam Wingard	\N
167	Christopher Nolan	\N
168	Christopher McQuarrie	\N
169	Clint Eastwood	\N
170	Rodrigo Cortés	\N
171	Barry Levinson	\N
172	Richard Gray	\N
173	Lars von Trier	\N
174	Nicholas Hytner	\N
175	Aaron Schimberg	\N
176	Kenji Kamiyama	\N
177	Ralph Bakshi	\N
178	Stephen Presley	\N
179	Henrik Burman	\N
180	Richard Fleischer	\N
181	John Milius	\N
182	Albert Pyun	\N
183	Sergey Bondarchuk	\N
184	Ron Howard	\N
185	Alex Proyas	\N
186	Rupert Sanders	\N
187	Denis Villeneuve	\N
188	Martin Scorsese	\N
189	Stanley Kubrick	\N
190	Peter Jackson	\N
191	Nicolas Winding Refn	\N
192	Paul Thomas Anderson	\N
193	David Lynch	\N
194	Sergio Leone	\N
195	David Lean	\N
196	Quentin Tarantino	\N
197	Michael Mann	\N
198	James Cameron	\N
199	Mary Harron	\N
200	Steven Spielberg	\N
201	Andrei Tarkovsky	\N
202	George Lucas	\N
203	Miloš Forman	\N
204	John McTiernan	\N
205	Damien Chazelle	\N
206	Andrew Dominik	\N
207	Park Chan-wook	\N
208	Akira Kurosawa	\N
209	Zack Snyder	\N
210	Hideaki Anno	\N
211	Irvin Kershner	\N
212	Ryan Coogler	\N
213	Frank Capra	\N
214	David Fincher	\N
215	Michel Gondry	\N
216	Masaki Kobayashi	\N
217	Dan Gilroy	\N
218	Brian Levant	\N
219	Sion Sono	\N
220	Peter Weir	\N
221	Sidney Lumet	\N
222	Ingmar Bergman	\N
223	Charlie Kaufman	\N
224	Bong Joon-ho	\N
225	Terrence Malick	\N
226	Oliver Stone	\N
227	Katsuhiro Otomo	\N
228	Martin McDonagh	\N
229	Paul Verhoeven	\N
230	John Boorman	\N
231	Jonathan Glazer	\N
232	Elem Klimov	\N
233	Sofia Coppola	\N
234	Wong Kar-wai	\N
235	Frank Darabont	\N
236	Jonathan Demme	\N
237	Andrew Niccol	\N
238	Fred M. Wilcox	\N
239	Shane Carruth	\N
240	Alfonso Cuarón	\N
241	Paul W. S. Anderson	\N
242	Neill Blomkamp	\N
243	Sebastián Cordero	\N
244	Duncan Jones	\N
245	Alex Garland	\N
246	Douglas Trumbull	\N
247	Nicholas Meyer	\N
248	Franklin J. Schaffner	\N
249	Joseph Kosinski	\N
250	Fritz Lang	\N
251	Andrew Stanton	\N
252	Mamoru Oshii	\N
253	Spike Jonze	\N
254	Robert Benton	\N
255	José Padilha	\N
256	Thomas Vinterberg	\N
257	Steve McQueen	\N
258	Jean-Marc Vallée	\N
259	Lee Jang-soo	\N
260	Darius Marder	\N
261	Heitor Dhalia	\N
262	Jean-Pierre Melville	\N
263	Penny Marshall	\N
264	Kevin Reynolds	\N
265	Michael Cimino	\N
266	Roland Joffé	\N
267	Max Barbakow	\N
268	Lexi Alexander	\N
269	John Badham	\N
270	John Ford	\N
271	John G. Avildsen	\N
272	John Hillcoat	\N
273	Mike Nichols	\N
274	Gavin O Connor	\N
275	Roman Polanski	\N
276	M. Night Shyamalan	\N
277	Matt Reeves	\N
278	Krzysztof Kieślowski	\N
279	Jeff Schaffer	\N
280	Robin Hardy	\N
281	Kenneth Lonergan	\N
282	Robert Zemeckis	\N
283	Cameron Crowe	\N
284	Sean Penn	\N
285	Nathan H. Juran	\N
286	Byron Haskin	\N
287	John Frankenheimer	\N
288	Hiroshi Teshigahara	\N
289	Roger Vadim	\N
290	Alain Resnais	\N
291	Michael Crichton	\N
292	Michael Anderson	\N
293	Nicolas Roeg	\N
294	Mike Hodges	\N
295	Steven Lisberger	\N
296	Andrzej Żuławski	\N
297	Richard Stanley	\N
298	Roland Emmerich	\N
299	Dean Parisot	\N
300	Richard Kelly	\N
301	Richard Linklater	\N
302	Satoshi Kon	\N
303	Mark Romanek	\N
304	Rian Johnson	\N
305	Doug Liman	\N
306	Gareth Edwards	\N
307	John Krasinski	\N
308	Claire Denis	\N
309	Andrew Patterson	\N
310	Brandon Cronenberg	\N
311	Neasa Hardiman	\N
312	Dan Trachtenberg	\N
313	Henri-Georges Clouzot	\N
314	Charles Laughton	\N
315	Georges Franju	\N
316	Michael Powell	\N
317	Alfred Hitchcock	\N
318	Jack Clayton	\N
319	Robert Aldrich	\N
320	Bob Clark	\N
321	Richard Donner	\N
322	Brian De Palma	\N
323	Don Coscarelli	\N
324	Peter Medak	\N
325	Sean S. Cunningham	\N
326	John Landis	\N
327	Frank Henenlotter	\N
328	Wes Craven	\N
329	Tom Holland	\N
330	Dan O Bannon	\N
331	Lamberto Bava	\N
332	Stuart Gordon	\N
333	Robert Harmon	\N
334	John McNaughton	\N
335	Sam Raimi	\N
336	George Sluizer	\N
337	Mary Lambert	\N
338	Rob Reiner	\N
339	Hideo Nakata	\N
340	Takashi Miike	\N
341	Alejandro Amenábar	\N
342	James Wan	\N
343	Edgar Wright	\N
344	Neil Marshall	\N
345	Rob Zombie	\N
346	Tomas Alfredson	\N
347	Mike Flanagan	\N
348	Patrick Brice	\N
349	Jennifer Kent	\N
350	Jordan Peele	\N
351	Andy Muschietti	\N
352	John C. Broderick	\N
353	Peter Yates	\N
354	Ernesto Díaz Espinoza	\N
355	Jack Hill	\N
356	Hugh Parks	\N
357	Matt Cimber	\N
358	Ernest Day	\N
359	Doug Lefler	\N
360	Joe Mari Avellana	\N
361	Tito Davison	\N
362	Rowdy Herrington	\N
363	Tony Scott	\N
364	Gordon Parks	\N
365	Jung Byung-gil	\N
366	Russell Mulcahy	\N
367	Renny Harlin	\N
368	Jon Turteltaub	\N
369	Prachya Pinkaew	\N
370	Robert Rodriguez	\N
371	King Hu	\N
372	Simon West	\N
373	Stephen Sommers	\N
374	Brett Ratner	\N
375	Antoine Fuqua	\N
376	Newt Arnold	\N
377	Stephen Norrington	\N
378	Michael Bay	\N
379	Paul Michael Glaser	\N
380	Andrew Davis	\N
381	Michael Davis	\N
382	Tim Burton	\N
383	Timur Bekmambetov	\N
384	Joss Whedon	\N
385	Walter Hill	\N
386	Kathryn Bigelow	\N
387	Pierre Morel	\N
388	Marco Brambilla	\N
389	Ilya Naishuller	\N
390	Jackie Chan	\N
391	Christophe Gans	\N
392	Matthew Vaughn	\N
393	David Leitch	\N
394	Stanley Tong	\N
395	Martin Brest	\N
396	Yuen Woo-ping	\N
397	Kinji Fukasaku	\N
398	Ringo Lam	\N
399	Stephen Chow	\N
400	John Woo	\N
401	Jon Favreau	\N
402	Timo Tjahjanto	\N
403	James Mangold	\N
404	Guy Hamilton	\N
405	Patty Jenkins	\N
406	Lo Wei	\N
407	Don Siegel	\N
408	Bryan Singer	\N
409	Wilson Yip	\N
410	Brad Bird	\N
411	Justin Lin	\N
412	Chad Stahelski	\N
413	Martin Campbell	\N
414	Gordon Chan	\N
415	Gareth Evans	\N
416	Robert Clouse	\N
417	Mark L. Lester	\N
418	Ted Kotcheff	\N
419	Jan de Bont	\N
420	Lau Kar-leung	\N
421	Ang Lee	\N
422	Paul Greengrass	\N
423	Mikael Håfström	\N
424	Breck Eisner	\N
425	Christopher Smith	\N
426	Vincenzo Natali	\N
427	Charles Martin Smith	\N
428	Bryn Higgins	\N
429	Brad Anderson	\N
430	Joel Anderson	\N
431	Chris Kentis	\N
432	Lucky McKee	\N
433	Andrew Douglas	\N
434	Steve De Jarnatt	\N
435	Oren Peli	\N
436	Mitchell Lichtenstein	\N
437	Bruce McDonald	\N
438	John Fawcett	\N
439	Michael Dougherty	\N
440	Irwin Allen	\N
441	Felix E. Feist	\N
442	Tetsuo Yoshida	\N
443	Gene Fowler Jr.	\N
444	Fred F. Sears	\N
445	William Cameron Menzies	\N
446	Terence Fisher	\N
447	Edward L. Cahn	\N
448	Henry Levin	\N
449	Stanley Kramer	\N
450	Ed Wood	\N
451	Harry Horner	\N
452	Phil Tucker	\N
453	Eugene Lourié	\N
454	Joseph Green	\N
455	Val Guest	\N
456	Edwin L. Marin	\N
457	Virgil W. Vogel	\N
458	Jun Fukuda	\N
459	George Pal	\N
460	Ranald MacDougall	\N
461	Gordon Douglas	\N
462	Wolf Rilla	\N
463	Rudolph Maté	\N
464	Roger Corman	\N
465	Guillermo del Toro	\N
466	David Bruckner	\N
467	Jean-Pierre Jeunet	\N
468	Fede Alvarez	\N
469	Martyn Burke	\N
470	Mick Garris	\N
471	Morten Tyldum	\N
472	Stephen Hopkins	\N
473	Nimród Antal	\N
474	Ian Nathan	\N
475	Shane Black	\N
476	Paul W.S. Anderson	\N
477	Steven Kostanski	\N
593	Danny Boyle	
594	Tod Browning	
595	Mario Bava	
596	Jack Arnold	
597	Joseph Kosinski	
598	Andy Sidaris	
599	Lee Cronin	
600	Joseph Kosinski	
601	Pete McCormack	
602		Peter Chung, Andrew R. Jones, Yoshiaki Kawajiri
603	Edgar G. Ulmer	
604	Xavier Gens	
605	Hugo Keijzer	
606	Mick Jackson	
607	Carl Theodor Dreyer	
12	Wolfgang Petersen	
\.


--
-- TOC entry 5069 (class 0 OID 16517)
-- Dependencies: 221
-- Data for Name: genres; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.genres (id, genre_name) FROM stdin;
\.


--
-- TOC entry 5071 (class 0 OID 16524)
-- Dependencies: 223
-- Data for Name: haswatched; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.haswatched (id, user_id, title_id, watch_date, watch_count, user_comment, user_rating, series_id) FROM stdin;
1	1	172	2025-12-01	1	Typical Sci Fi movie from 80s/90s it was worth watching	3.0	\N
2	1	173	2025-12-04	1	An average horror movie	3.0	\N
3	1	7563	2025-12-14	1	I am still preferring the 40s version	3.0	\N
4	1	7564	2025-12-17	1	Amazing, its perfect	5.0	\N
5	1	7565	2025-12-23	1	Not so good	3.0	\N
6	1	131	2025-12-23	3	Love it	4.0	\N
7	1	117	2024-01-01	1	Love it, but could have been better and I have forgotten the exact day I watched it	4.0	\N
8	1	116	2024-01-01	1	Love it	4.0	\N
9	1	134	2024-01-01	1	Love it	4.0	\N
10	1	226	2024-01-01	1	Must have watched lots of time, but never in english	5.0	\N
11	1	127	2024-01-01	1	Love it	4.0	\N
12	2	119	2025-12-28	1	Um clássico!	5.0	\N
13	2	6	2025-05-28	1	Muito bom, hostei	3.0	\N
14	2	203	2020-12-28	1	Não entendi nada	5.0	\N
15	5	42	2024-01-01	1	Muito legal	4.0	\N
16	5	13	2025-12-28	1	Muito bom	5.0	\N
17	3	8	2020-09-30	1	loved to see it in  the cinema	4.0	\N
18	3	46	2024-12-20	1	Very interesting	4.0	\N
19	4	4694	2025-12-28	1	One of the best movies of all time	5.0	\N
20	4	143	2025-12-28	1	Liked it very much	5.0	\N
21	1	\N	2025-12-25	1	<3	4.0	22
22	1	7567	2025-12-30	2	has some positive and negative points, its worth watching but not surpass the olders	3.0	\N
23	1	7566	2025-12-31	1	It was good to watch	4.0	\N
24	1	529	2025-12-29	1	Sci-fi combined with action, great movie	5.0	\N
25	1	227	2025-12-28	1	One of my favorites	5.0	\N
30	1	7569	2026-01-04	1	it was interesting, way better than alien 3	3.0	\N
31	1	7572	2026-01-03	1	The worst of the series	2.0	\N
32	1	7571	2026-01-02	1	Cool but following the same premise	4.0	\N
33	1	7566	2026-01-01	1	Cool	4.0	\N
34	1	238	2026-01-05	1	This movie is just perfect	5.0	\N
35	1	7591	2026-01-06	1	Although not as good as the first one, it starts a bit \\"Okay\\", but the film grows up and gives an amazing experience	4.0	\N
36	1	7592	2026-01-06	1	Not so good, but not so bad as it appears to be	3.0	\N
37	1	7593	2025-12-29	1	Méhhhhh	3.0	\N
38	1	7599	2026-01-08	1	Not to take to seriously	\N	\N
39	1	7600	2026-01-10	1	Interesting	\N	\N
40	1	7601	2026-01-11	1	The has a serious problem with brightness	\N	\N
41	1	7602	2026-01-12	1	Nothing special, just an adventure movie 	\N	\N
42	1	3747	2026-01-13	2	Too much action, interesting movie	\N	\N
43	1	4346	2026-01-15	1	Too much nudism (Im not complaining)	\N	\N
44	1	1	2026-01-17	1	One of my favorite generes and movie	10.0	\N
45	1	7598	2026-01-21	1	Too long	10.0	\N
46	1	7604	2026-01-23	1	Just another modern movie	6.0	\N
47	1	117	2026-01-23	2	Amazing	8.9	\N
48	1	7603	2026-01-18	1	Theres no comparison with the original one. Loved the practical effects	7.5	\N
49	1	4039	2026-01-30	2	One of my favorites	10.0	\N
50	1	7605	2026-01-29	1	An generic Sci-Fi Movie	6.0	\N
51	1	7580	2026-01-27	1	Cool, I would love to have a gun that explodes targets with a single bullet	7.5	\N
52	1	7606	2026-01-26	1	Too dark, old CGI	6.0	\N
53	1	\N	2025-12-20	2	Love it	9.5	12
54	1	7877	2026-01-31	1	A really nice experience	8.5	\N
55	1	7878	2026-02-04	1	Cool but, generic	6.5	\N
56	1	7884	2026-02-07	1	Interesting	8.0	\N
57	1	7885	2026-02-01	2	Cool	7.5	\N
58	1	7886	2026-02-06	2	the type of experience that you should only try once, it illustrates relationship between humans problems	7.0	\N
59	1	7889	2026-02-03	2	I like this film very mutch, it has some Blair Wich experience	8.5	\N
62	1	201	2026-02-10	2	Cool	9.0	\N
63	1	204	2026-02-11	2	Cool too	9.0	\N
64	1	7872	2026-02-15	2	Second time I watch, second time I sleep	6.0	\N
65	1	7873	2026-02-14	1	Stupid and 90% Soft porn	5.0	\N
66	1	7880	2026-02-12	2	Nice sequence	8.5	\N
67	1	7882	2026-02-09	2	Cool	7.8	\N
\.


--
-- TOC entry 5073 (class 0 OID 16534)
-- Dependencies: 225
-- Data for Name: series; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.series (id, series_name, creator, genre, year_release, seasons, episodes, season_ended) FROM stdin;
12	Alien: Earth	Noah Hawley	Sci Fi/Horror/Thriller/Slasher	2025	0	0	YES
13	True Detective	Nic Pizzolatto/Issa López	Crime	2014	0	0	YES
14	The Outer Limits	Leslie Stevens	Sci Fi	1995	0	0	YES
15	The Simpsons	Matt Groening/James L. Brooks/Sam Simon	Animation	1989	0	0	NO
16	The X Files	Chris Carter	Sci Fi/Crime	1993	0	0	YES
17	Millennium	Chris Carter	Sci Fi/Crime	1996	0	0	YES
18	Lost	J.J. Abrams/Jeffrey Lieber/Damon Lindelof	Sci Fi/Drama/Mystery/Adventure	2004	0	0	YES
19	The Walking Dead	Frank Darabont	Apocalyptic/Zombie/Zombie Drama/Horror/Thriller/Dystopian	2010	0	0	YES
20	Breaking Bad	Vince Gilligan	Sci Fi/Drama/Crime	2008	0	0	YES
21	Game Of Thrones	David Benioff/D.B. Weiss	Epic/Fantasy/Dark Fantasy/Drama	2011	0	0	YES
22	Pluribus	Vince Gilligan	Dystopian Sci Fi/Sci Fi	2025	1	9	YES
23	It: Welcome to Derry	Jason Fuchs, Andy Muschietti, Barbara Muschietti	Horror/Thriller	2025	1	8	YES
24	A Knight of the Seven Kingdoms	George R.R. Martin, Ira Parker	Action/Adventure/Drama/Fantasy	2026	1	3	NO
\.


--
-- TOC entry 5075 (class 0 OID 16549)
-- Dependencies: 227
-- Data for Name: titles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.titles (id, title, director_id, genre, year_release, synopsis, category, runtime, genres) FROM stdin;
1	Blair Witch	41	Found Footage	1999		Movie	0.00	\N
2	The Pyramid	11	Horror/Adventure/Found Footage	2014		Movie	0.00	\N
3	The Sacrament	15	Horror/Drama/Found Footage	2013		Movie	0.00	\N
4	The Incantation	18	Horror/Adventure/Found Footage	2018		Movie	0.00	\N
5	V/H/S: Beyond	16	Found Footage	2024		Movie	0.00	\N
6	V/H/S: Halloween	17	Found Footage	2025		Movie	0.00	\N
7	Enemy Mine	12	Sci-Fi	1985		Movie	0.00	\N
8	Body Snatchers	13	Sci-Fi	1993		Movie	0.00	\N
9	Lifeforce	14	Sci-Fi	1985		Movie	0.00	\N
10	Batteries Not Included	83	Sci-Fi	1987		Movie	0.00	\N
11	The Blob	84	Sci-Fi	1988		Movie	0.00	\N
12	Flight of the Navigator 	85	Sci-Fi	1986		Movie	0.00	\N
13	Starman	86	Sci-Fi	1984		Movie	0.00	\N
14	The Ice Pirates	87	Sci-Fi	1984		Movie	0.00	\N
15	Heavy Metal	19	Sci-Fi/Animation	1981		Animation	0.00	\N
16	Heavy Metal 2	20	Sci-Fi/Animation	2000		Animation	0.00	\N
17	Repo Men	88	Sci-Fi	1984		Movie	0.00	\N
18	The Hidden	89	Sci-Fi	1987		Movie	0.00	\N
19	Brazil	90	Sci-Fi	1985		Movie	0.00	\N
20	The Fifth Element	91	Sci-Fi	1997		Movie	0.00	\N
21	The Day The Earth Stood Still (Remake)	92	Sci-Fi	2008		Movie	0.00	\N
22	Dredd 2	93	Sci-Fi	2012		Movie	0.00	\N
23	Solaris	94	Sci-Fi	2002		Movie	0.00	\N
24	Fly Me To The Moon	95	Sci-Fi	2024		Movie	0.00	\N
25	Ad Astra	96	Sci-Fi	2019		Movie	0.00	\N
26	Equilibrium	97	Sci-Fi	2005		Movie	0.00	\N
27	Kingdom Of The Planet Of The Apes	98	Sci-Fi	2024		Movie	0.00	\N
28	Leave The World Behind	99	Sci-Fi	2023		Movie	0.00	\N
29	Megalopolis	100	Sci-Fi	2024		Movie	0.00	\N
30	The Day The Earth Stood Still	101	Sci-Fi	1951		Movie	0.00	\N
31	The Thing From Another World	21	Sci-Fi	1951		Movie	0.00	\N
32	The Thing	86	Sci-Fi	1982		Movie	0.00	\N
33	The Fly I	102	Sci-Fi	1986		Movie	0.00	\N
34	The Fly II	103	Sci-Fi	1989		Movie	0.00	\N
35	Alienator	104	Sci-Fi	1990		Movie	0.00	\N
36	Elevation	105	Sci-Fi	2024		Movie	0.00	\N
37	Companion	106	Sci-Fi	2025		Movie	0.00	\N
38	The Dark And The Wicked	107	Horror/Thriller	2020		Movie	0.00	\N
39	Frankenstein	108	Horror/Thriller	2015		Movie	0.00	\N
40	Midsommar	109	Horror/Thriller	2019		Movie	0.00	\N
41	In A Violent Nature	110	Horror/Thriller	2024		Movie	0.00	\N
42	MaXXXine	15	Horror/Thriller	2024		Movie	0.00	\N
43	The Watchers	111	Horror/Thriller	2024		Movie	0.00	\N
44	Bird Box	112	Horror/Thriller/Sci-Fi	2018		Movie	0.00	\N
45	The House Of The Devil	15	Horror/Thriller	2009		Movie	0.00	\N
46	Longlegss	113	Horror/Thriller	2024		Movie	0.00	\N
47	Apartment 7A	114	Horror/Thriller	2024		Movie	0.00	\N
48	The Substance	115	Horror/Thriller	2024		Movie	0.00	\N
49	Speak No Evil (Remake)	116	Horror/Thriller	2024		Movie	0.00	\N
50	Never Let Go	117	Horror/Thriller	2024		Movie	0.00	\N
51	Shutter	22	Horror/Thriller	2004		Movie	0.00	\N
52	Lights Out	118	Horror/Thriller	2016		Movie	0.00	\N
53	It Follows	119	Horror/Thriller/Mystery/Suspense	2015		Movie	0.00	\N
54	Antrum: The Deadliest Film Ever Made	23	Horror/Documentary	2018		Movie	0.00	\N
55	As Above So Below	120	Found Footage	2015		Movie	0.00	\N
56	Frogman	121	Found Footage	2023		Movie	0.00	\N
59	Megan Is Missing	122	Found Footage	2011		Movie	0.00	\N
60	Invasion Of The Body Snatchers	123	Horror/Thriller/Sci-Fi	1978		Movie	0.00	\N
61	Speak No Evil	124	Horror/Thriller	2022		Movie	0.00	\N
62	Mad Max 1	125	Action/Sci-Fi	1979		Movie	0.00	\N
63	Ben-Hur	126	Action/Adventure	1959		Movie	0.00	\N
64	Judge Dredd	127	Sci-Fi/Action	1995		Movie	0.00	\N
65	Vampires	86	Horror/Thriller	1998		Movie	0.00	\N
66	In The Mouth Of Madness	86	Horror/Thriller/Cosmic Horror	1994		Movie	0.00	\N
67	Atrocious	128	Found Footage	2010		Movie	0.00	\N
68	August Undergrounds Mordum	24	Found Fotage/Horror/Slasher	2003		Movie	0.00	\N
69	Be My Cat	129	Found Footage	2015		Movie	0.00	\N
70	The Taking Of Deborah Logan	130	Horror/Thriller/Found Footage	2015		Movie	0.00	\N
71	Diary of The Dead	131	Horror/Sci-Fi/Found Footage	2007		Movie	0.00	\N
72	Grave Encounters	25	Found Footage/Horror	2011		Movie	0.00	\N
73	The Houses October Built	132	Horror/Suspense	2014		Movie	0.00	\N
74	The Poughkeepsie Tapes	120	Horror/Mistery	2007		Movie	0.00	\N
75	Host	133	Horror/Mistery	2020		Movie	0.00	\N
106	Daddys Head	134	Horror/Thriller	2024		Movie	0.00	\N
107	Carnage	135	Horror/Thriller	1984		Movie	0.00	\N
108	Cruising	136	Crime/Horror/Thriller	1980		Movie	0.00	\N
109	End of Days	137	Horror/Thriller	1999		Movie	0.00	\N
110	Blink Twice	138	Horror/Thriller	2024		Movie	0.00	\N
111	Y2K	139	Horror/Thriller/Sci-Fi	2024		Movie	0.00	\N
112	Frankenstein (1981)	140	Horror/Thriller/Sci-Fi	1981		Movie	0.00	\N
113	Dracula	26	Horror/Thriller	1931		Movie	0.00	\N
114	Freaks	594	Horror/Thriller	1931		Movie	0.00	\N
115	The Old Dark house	141	Horror/Thriller	1931		Movie	0.00	\N
116	The Bride Of Frankenstein	140	Horror/Thriller	1935		Movie	0.00	\N
117	Nosferatu	142	Horror/Thriller	2024		Movie	0.00	\N
118	The Omega Man	143	Horror/Thriller/Sci-Fi/Dystopian	1971		Movie	0.00	\N
119	Suspiria	144	Horror/Thriller	1977		Movie	0.00	\N
120	Suspiria (2018)	145	Horror/Thriller	2018		Movie	0.00	\N
121	Tusk	146	Horror/Thriller	2014		Movie	0.00	\N
122	Pulse	147	Horror/Thriller	2001		Movie	0.00	\N
123	Cure	147	Horror/Thriller	1997		Movie	0.00	\N
124	Heretic	27	Horror/Thriller	2024		Movie	0.00	\N
125	Smile 2	148	Horror/Thriller	2024		Movie	0.00	\N
126	Wolfman	149	Horror/Thriller	2025		Movie	0.00	\N
127	The Wolfman	150	Horror/Thriller	1941		Movie	0.00	\N
128	Final Destination: Bloodlines	151	Horror/Thriller	2025		Movie	0.00	\N
129	Dead of Night	28	Horror/Thriller	1945		Movie	0.00	\N
130	House of Wax	152	Horror/Thriller	1953		Movie	0.00	\N
131	I walked with a Zombie	153	Horror/Thriller	1943		Movie	0.00	\N
132	Jacob’s Ladder	154	Horror/Thriller	1990		Movie	0.00	\N
133	Lord of Illusions	155	Horror/Thriller	1995		Movie	0.00	\N
134	The Invisible man	140	Horror/Thriller	1933		Movie	0.00	\N
135	Eddington	109	Drama	2025		Movie	0.00	\N
136	Bring Her Back	29	Horror/Thriller	2025		Movie	0.00	\N
137	28 Years Later	593	Horror/Thriller	2025		Movie	0.00	\N
138	Weapons	156	Horror/Thriller	2025		Movie	0.00	\N
139	The Conjuring: Last Rites	157	Horror/Thriller	2025		Movie	0.00	\N
140	Apocalypto	158	Horror/Thriller	2006		Movie	0.00	\N
141	Fear Below	159	Horror/Thriller	2025		Movie	0.00	\N
142	Venom: The Last Dance	160	Action	2024		Movie	0.00	\N
143	Gladiador II	161	Action	2024		Movie	0.00	\N
144	Falling Down	162	Action	1993		Movie	0.00	\N
145	The Eagle	163	Action	2011		Movie	0.00	\N
146	Kraven	164	Action	2024		Movie	0.00	\N
147	Armor	165	Action	2024		Movie	0.00	\N
148	Godzilla X Kong: The New Empire	166	Action	2024		Movie	0.00	\N
149	Tenet	167	Action	2020		Movie	0.00	\N
150	Mission Impossible: The Final Reckoning	168	Action	2024		Movie	0.00	\N
151	Mystic River	169	Crime/Drame	2003		Movie	0.00	\N
152	Red Lights	170	Crime/Drama	2012		Movie	0.00	\N
153	The Alto Knights	171	Crime	2025		Movie	0.00	\N
154	The Unholy Trinity	172	Crime	2025		Movie	0.00	\N
155	Legend	161	Dark Fantasy	1985		Movie	0.00	\N
156	The Dark Crystal	30	Dark Fantasy	1982		Movie	0.00	\N
157	The Never Ending Story	12	Dark Fantasy	1984		Movie	0.00	\N
158	Melancholia	173	Drama	2011		Movie	0.00	\N
159	The Crucible	174	Drama	1996		Movie	0.00	\N
160	A Different Man	175	Drama	2024		Movie	0.00	\N
161	Slumdog Millionaire	31	Drama	2008		Movie	0.00	\N
162	The Lord Of The Rings: The War Of Rohirrim	176	Epic/Fantasy/Dark Fantasy/Medieval	2024		Animation	0.00	\N
163	The Lord Of The Rings	177	Epic/Fantasy/Dark Fantasy/Medieval	1978		Animation	0.00	\N
164	Pandemic: The People, The Conspiracy, The Journey	178	Documentary/Drama	2020		Documentary	0.00	\N
165	Avicii: Im Tim	179	Documentary/Biography	2024		Documentary	0.00	\N
166	Conan: The Destroyer	180	Medieval/Dark Fantasy	1984		Movie	0.00	\N
167	Conan: The Barbarian	181	Medieval/Dark Fantasy	1982		Movie	0.00	\N
168	The Northman	142	Medieval	2024		Movie	0.00	\N
169	The Sword And The Sorcerer	182	Medieval/Dark Fantasy	1982		Movie	0.00	\N
170	Waterloo	183	War	1970		Movie	0.00	\N
171	Cinderela Man	184	Biography/Drama	2005		Movie	0.00	\N
172	Time Cop	137	Sci-Fi/Crime	1994		Movie	0.00	\N
173	Black Phone 2	92	Horror/Thriller	2025		Movie	0.00	\N
174	Dark City	185	Mitery/Sci-Fi	1998		Movie	0.00	\N
175	Ghost In The Shell	186	Action/Sci-Fi	2017		Movie	0.00	\N
201	Blade Runner 2049	187	Sci-Fi	2017		Movie	0.00	\N
202	Taxi Driver	188	Drama/Crime	1976		Movie	0.00	\N
203	2001: A Space Odyssey	189	Sci-Fi	1968		Movie	0.00	\N
204	Blade Runner	161	Sci-Fi	1982		Movie	0.00	\N
205	Lord Of The Rings: Fellowship of the Ring	190	Fantasy	2001		Movie	0.00	\N
206	Drive	191	Crime/Drama	2011		Movie	0.00	\N
207	Apocalypse Now	100	War/Drama	1979		Movie	0.00	\N
208	There Will Be Blood	192	Drama	2007		Movie	0.00	\N
209	Mulholland Drive	193	Mystery/Thriller	2001		Movie	0.00	\N
210	The Good, The Bad and the Ugly	194	Western	1966		Movie	0.00	\N
211	Eyes Wide Shut	189	Drama/Mystery	1999		Movie	0.00	\N
212	The Dark Knight Rises	167	Action	2012		Movie	0.00	\N
213	No Country For Old Men	32	Crime/Thriller	2007		Movie	0.00	\N
214	Das Boot	12	War/Drama	1981		Movie	0.00	\N
215	Goodfellas	188	Crime/Drama	1990		Movie	0.00	\N
216	Lawrence Of Arabia	195	Adventure/Drama	1962		Movie	0.00	\N
217	Barry Lyndon	189	Drama	1975		Movie	0.00	\N
218	The Godfather	100	Crime/Drama	1972		Movie	0.00	\N
219	Pulp Fiction	196	Crime	1994		Movie	0.00	\N
220	Heat	197	Crime/Action	1995		Movie	0.00	\N
221	Terminator 2	198	Sci-Fi/Action	1991		Movie	0.00	\N
222	The Shining	189	Horror	1980		Movie	0.00	\N
223	Gladiator	161	Action/Drama	2000		Movie	0.00	\N
224	For A Few Dollars More	194	Western	1965		Movie	0.00	\N
225	American Psycho	199	Thriller	2000		Movie	0.00	\N
226	The Matrix	33	Sci-Fi	1999		Movie	0.00	\N
227	Alien	161	Sci-Fi/Horror	1979		Movie	0.00	\N
228	Jurassic Park	200	Sci-Fi/Adventure/Dinosaur	1993		Movie	0.00	\N
229	Stalker	201	Sci-Fi/Drama	1979		Movie	0.00	\N
230	Star Wars - A New Hope	202	Sci-Fi	1977		Movie	0.00	\N
231	Amadeus	203	Drama/Biography	1984		Movie	0.00	\N
232	Die Hard	204	Action	1988		Movie	0.00	\N
233	Star Wars - Revenge of the Sith	202	Sci-Fi	2005		Movie	0.00	\N
234	La La Land	205	Musical/Romance	2016		Movie	0.00	\N
235	The Dark Knight	167	Action/Crime	2008		Movie	0.00	\N
236	A Clockwork Orange	189	Sci-Fi/Crime	1971		Movie	0.00	\N
237	Once Upon a Time in America	194	Crime/Drama	1984		Movie	0.00	\N
238	Predator	204	Sci-Fi/Action	1987		Movie	0.00	\N
239	The Assassination Of Jesse James..	206	Western/Drama	2007		Movie	0.00	\N
240	Oldboy	207	Thriller	2003		Movie	0.00	\N
241	Lord of the Rings: Return of the King	190	Fantasy	2003		Movie	0.00	\N
242	Lord of the Rings: The Two Towers	190	Fantasy	2002		Movie	0.00	\N
243	Seven Samurai	208	Adventure/Drama	1954		Movie	0.00	\N
244	Batman Vs Superman	209	Action/Superhero	2016		Movie	0.00	\N
245	The End of Evangelion	210	Animation/Sci-Fi	1997		Animation	0.00	\N
246	Blue Velvet	193	Mystery/Thriller	1986		Movie	0.00	\N
247	The Big Lebowski	32	Comedy	1998		Movie	0.00	\N
248	Star Wars: Empire Strikes Back	211	Sci-Fi	1980		Movie	0.00	\N
249	Black Panther	212	Action/Superhero	2018		Movie	0.00	\N
327	The Godfather: Part II	100	Crime/Drama	1974		Movie	0.00	\N
328	Eraserhead	193	Horror	1977		Movie	0.00	\N
329	Casino	188	Crime/Drama	1995		Movie	0.00	\N
330	Its A Wonderful Life	213	Drama/Fantasy	1946		Movie	0.00	\N
331	Fight Club	214	Drama	1999		Movie	0.00	\N
332	Eternal Sunshine of a Spotless Mind	215	Romance/Drama	2004		Movie	0.00	\N
333	Harakiri	216	Drama	1962		Movie	0.00	\N
334	Only God Forgives	191	Crime/Drama	2013		Movie	0.00	\N
335	Nightcrawler	217	Thriller	2014		Movie	0.00	\N
336	Ikiru	208	Drama	1952		Movie	0.00	\N
337	Problem Child 2	218	Comedy	1991		Movie	0.00	\N
338	Love Exposure	219	Drama	2008		Movie	0.00	\N
339	Master and Commander	220	Adventure/Drama	2003		Movie	0.00	\N
340	12 Angry Men	221	Drama	1957		Movie	0.00	\N
341	Persona	222	Drama	1966		Movie	0.00	\N
342	Wild Strawberries	222	Drama	1957		Movie	0.00	\N
343	Synecdoche, New York	223	Drama	2008		Movie	0.00	\N
344	Memories of Murder	224	Crime/Thriller	2003		Movie	0.00	\N
345	One Flew Over the Cuckoos Nest	203	Drama	1975		Movie	0.00	\N
346	The House That Jack Built	173	Horror/Drama	2018		Movie	0.00	\N
347	The Tree of Life	225	Drama	2011		Movie	0.00	\N
348	300	209	Action	2006		Movie	0.00	\N
349	Platoon	226	War/Drama	1986		Movie	0.00	\N
350	Akira	227	Sci-Fi	1988		Animation	0.00	\N
351	Whiplash	205	Drama	2014		Movie	0.00	\N
352	In Bruges	228	Comedy/Crime	2008		Movie	0.00	\N
353	Robocop	229	Sci-Fi/Action	1987		Movie	0.00	\N
354	Excalibur	230	Fantasy	1981		Movie	0.00	\N
355	City of God	35	Crime/Drama	2002		Movie	0.00	\N
356	Interstellar	167	Sci-Fi	2014		Movie	0.00	\N
357	Under the Skin	231	Sci-Fi	2013		Movie	0.00	\N
358	Come and See	232	War/Drama	1985		Movie	0.00	\N
359	Lost in Translation	233	Drama/Romance	2003		Movie	0.00	\N
360	Mirror	201	Drama	1975		Movie	0.00	\N
361	Chungking Express	234	Drama/Romance	1994		Movie	0.00	\N
362	The Shawshank Redemption	235	Drama	1994		Movie	0.00	\N
363	The Silence of the Lambs	236	Thriller	1991		Movie	0.00	\N
529	Aliens	198	Sci-Fi	1986		Movie	0.00	\N
530	Gattaca	237	Sci-Fi	1997		Movie	0.00	\N
531	Forbidden Planet	238	Sci-Fi	1956		Movie	0.00	\N
532	Primer	239	Sci-Fi	2004		Movie	0.00	\N
533	Children of Men	240	Sci-Fi	2006		Movie	0.00	\N
534	Dune	193	Sci-Fi	1984		Movie	0.00	\N
535	Event Horizon	241	Sci-Fi/Horror	1997		Movie	0.00	\N
536	District 9	242	Sci-Fi	2009		Movie	0.00	\N
537	Europa Report	243	Sci-Fi	2013		Movie	0.00	\N
538	Gravity	240	Sci-Fi	2013		Movie	0.00	\N
539	Sunshine	593	Sci-Fi	2007	A team of international astronauts is sent on a dangerous mission to reignite the dying Sun with a nuclear fission bomb in 2057.	Movie	0.00	\N
540	Moon	244	Sci-Fi	2009		Movie	0.00	\N
541	Ex Machina	245	Sci-Fi	2014		Movie	0.00	\N
542	A.I.	200	Sci-Fi	2001		Movie	0.00	\N
543	Minority Report	200	Sci-Fi	2002		Movie	0.00	\N
544	Total Recall	229	Sci-Fi	1990		Movie	0.00	\N
545	Avatar	198	Sci-Fi	2009		Movie	0.00	\N
546	Silent Running	246	Sci-Fi	1972		Movie	0.00	\N
547	12 Monkeys	90	Sci-Fi	1995		Movie	0.00	\N
548	Escape from New York	86	Sci-Fi/Action	1981		Movie	0.00	\N
549	Star Trek: The Motion Picture	101	Sci-Fi	1979		Movie	0.00	\N
550	Star Trek II: The Wrath of Khan	247	Sci-Fi	1982		Movie	0.00	\N
551	Planet of the Apes	248	Sci-Fi	1968		Movie	0.00	\N
552	Tron: Legacy	249	Sci-Fi	2010		Movie	0.00	\N
553	Elysium	242	Sci-Fi	2013		Movie	0.00	\N
554	The Martian	161	Sci-Fi	2015		Movie	0.00	\N
555	The Terminator	198	Sci-Fi	1984		Movie	0.00	\N
556	Terminator 2: Judgment Day	198	Sci-Fi	1991		Movie	0.00	\N
557	Metropolis	250	Sci-Fi	1927		Movie	0.00	\N
558	WALL-E	251	Sci-Fi	2008		Movie	0.00	\N
559	Ghost in the Shell (1995)	252	Sci-Fi	1995		Animation	0.00	\N
689	Her	253	Romance/Drama	2013		Movie	0.00	\N
690	Kramer Vs. Kramer	254	Drama	1979		Movie	0.00	\N
691	Tropa de Elite	255	Crime/Drama	2007		Movie	0.00	\N
692	The Hunt	256	Drama	2012		Movie	0.00	\N
693	Shame	257	Drama	2011		Movie	0.00	\N
694	Under the Silver Lake	119	Mystery/Thriller	2018		Movie	0.00	\N
695	Full Metal Jacket	189	War/Drama	1987		Movie	0.00	\N
696	Demolition	258	Drama	2015		Movie	0.00	\N
697	Be With You	259	Romance/Drama	2004		Movie	0.00	\N
698	Sound of Metal	260	Drama	2019		Movie	0.00	\N
699	O Cheiro do Ralo	261	Drama	2006		Movie	0.00	\N
700	Le Samouraï	262	Crime/Thriller	1967		Movie	0.00	\N
701	Awakenings	263	Drama	1990		Movie	0.00	\N
702	Call Me By Your Name	145	Romance/Drama	2017		Movie	0.00	\N
703	The Count of Monte Cristo	264	Adventure	2002		Movie	0.00	\N
704	The Deer Hunter	265	Drama/War	1978		Movie	0.00	\N
705	The Truman Show	220	Drama	1998		Movie	0.00	\N
706	The Bridge on the River Kwai	195	War/Drama	1957		Movie	0.00	\N
707	The Killing Fields	266	Drama/War	1984		Movie	0.00	\N
708	Palm Springs	267	Romance/Comedy	2020		Movie	0.00	\N
709	Rush	184	Drama/Sport	2013		Movie	0.00	\N
710	The Passion of the Christ	158	Drama	2004		Movie	0.00	\N
711	Green Street Hooligans	268	Drama/Crime	2005		Movie	0.00	\N
712	Enemy	187	Thriller	2013		Movie	0.00	\N
713	Saturday Night Fever	269	Drama/Music	1977		Movie	0.00	\N
714	The Searchers	270	Western	1956		Movie	0.00	\N
715	Rocky	271	Drama/Sport	1976		Movie	0.00	\N
716	The Road	272	Drama	2009		Movie	0.00	\N
717	The Graduate	273	Comedy/Drama	1967		Movie	0.00	\N
718	Warrior	274	Drama/Sport	2011		Movie	0.00	\N
719	The Pianist	275	Drama/War	2002		Movie	0.00	\N
720	Unbreakable	276	Thriller	2000		Movie	0.00	\N
721	Fargo	32	Crime/Drama	1996		Movie	0.00	\N
722	Cloverfield	277	Thriller	2008		Movie	0.00	\N
723	Trois Couleurs: Blanc	278	Drama	1994		Movie	0.00	\N
724	Eurotrip	279	Comedy	2004		Movie	0.00	\N
725	The Wicker Man	280	Horror	1973		Movie	0.00	\N
726	Manchester by the Sea	281	Drama	2016		Movie	0.00	\N
727	Cast Away	282	Drama	2000		Movie	0.00	\N
728	Vanilla Sky	283	Drama/Romance	2001		Movie	0.00	\N
729	Into the Wild	284	Adventure/Drama	2007		Movie	0.00	\N
3696	Attack of the 50ft Woman	285	Sci-Fi	1958		Movie	0.00	\N
3697	Robinson Crusoe on Mars	286	Sci-Fi	1964		Movie	0.00	\N
3698	Seconds	287	Sci-Fi	1966		Movie	0.00	\N
3699	The Face of Another	288	Sci-Fi	1966		Movie	0.00	\N
3700	Barbarella	289	Sci-Fi	1968		Movie	0.00	\N
3701	Je taime, Je taime	290	Sci-Fi	1968		Movie	0.00	\N
3702	Westworld	291	Sci-Fi	1973		Movie	0.00	\N
3703	Dark Star	86	Sci-Fi	1974		Movie	0.00	\N
3704	Logans Run	292	Sci-Fi	1976		Movie	0.00	\N
3705	The Man Who Fell to Earth	293	Sci-Fi	1976		Movie	0.00	\N
3706	Close Encounters of the Third Kind	200	Sci-Fi	1977		Movie	0.00	\N
3707	Star Wars: A New Hope	202	Sci-Fi	1977		Movie	0.00	\N
3708	Mad Max	125	Sci-Fi/Action	1979		Movie	0.00	\N
3709	Flash Gordon	294	Sci-Fi	1980		Movie	0.00	\N
3710	Star Wars: The Empire Strikes Back	211	Sci-Fi	1980		Movie	0.00	\N
3711	Outland	137	Sci-Fi	1981		Movie	0.00	\N
3712	E.T.	200	Sci-Fi	1982		Movie	0.00	\N
3713	Tron	295	Sci-Fi	1982		Movie	0.00	\N
3714	Videodrome	102	Sci-Fi	1983		Movie	0.00	\N
3715	2010	137	Sci-Fi	1984		Movie	0.00	\N
3716	Back to the Future	282	Sci-Fi	1985		Movie	0.00	\N
3718	They Live	86	Sci-Fi/Action	1988		Movie	0.00	\N
3719	On the Silver Globe	296	Sci-Fi	1989		Movie	0.00	\N
3720	Hardware	297	Sci-Fi	1990		Movie	0.00	\N
3721	Stargate	298	Sci-Fi	1994		Movie	0.00	\N
3722	Contact	282	Sci-Fi	1997		Movie	0.00	\N
3723	eXistenZ	102	Sci-Fi	1999		Movie	0.00	\N
3724	Galaxy Quest	299	Sci-Fi	1999		Movie	0.00	\N
3725	Donnie Darko	300	Sci-Fi	2001		Movie	0.00	\N
3726	Eternal Sunshine of the Spotless Mind	215	Romance/Drama	2004		Movie	0.00	\N
3727	A Scanner Darkly	301	Sci-Fi	2006		Movie	0.00	\N
3728	Paprika	302	Sci-Fi	2006		Animation	0.00	\N
3729	Inception	167	Sci-Fi	2010		Movie	0.00	\N
3730	Never Let Me Go	303	Sci-Fi/Drama	2010		Movie	0.00	\N
3731	Looper	304	Sci-Fi	2012		Movie	0.00	\N
3732	Spring	37	Sci-Fi/Romance	2014		Movie	0.00	\N
3733	Edge of Tomorrow	305	Sci-Fi	2014		Movie	0.00	\N
3734	Predestination	38	Sci-Fi	2014		Movie	0.00	\N
3735	Mad Max: Fury Road	125	Sci-Fi/Action	2015		Movie	0.00	\N
3736	Arrival	187	Sci-Fi	2016		Movie	0.00	\N
3737	Rogue One: A Star Wars Story	306	Sci-Fi	2016		Movie	0.00	\N
3738	Okja	224	Sci-Fi	2017		Movie	0.00	\N
3739	Annihilation	245	Sci-Fi	2018		Movie	0.00	\N
3740	A Quiet Place	307	Sci-Fi/Horror	2018		Movie	0.00	\N
3741	High Life	308	Sci-Fi	2018		Movie	0.00	\N
3742	Prospect	39	Sci-Fi	2018		Movie	0.00	\N
3743	The Vast of Night	309	Sci-Fi	2019		Movie	0.00	\N
3744	Possessor	310	Sci-Fi	2020		Movie	0.00	\N
3745	Sea Fever	311	Sci-Fi/Horror	2020		Movie	0.00	\N
3746	Synchronic	37	Sci-Fi	2020		Movie	0.00	\N
3747	Prey/Skull	312	Sci-Fi/Action	2022		Movie	0.00	\N
3817	Les Diaboliques	313	Mystery/Horror/Thriller	1955		Movie	0.00	\N
3818	The Night of the Hunter	314	Mystery/Horror/Thriller	1955		Movie	0.00	\N
3819	House on Haunted Hill	141	Mystery/Horror/Thriller	1959		Movie	0.00	\N
3820	Eyes Without a Face	315	Mystery/Horror/Thriller	1960		Movie	0.00	\N
3821	Peeping Tom	316	Mystery/Horror/Thriller	1960		Movie	0.00	\N
3822	Psycho	317	Mystery/Horror/Thriller	1960		Movie	0.00	\N
3823	The Innocents	318	Mystery/Horror/Thriller	1961		Movie	0.00	\N
3824	What Ever Happened to Baby Jane?	319	Mystery/Horror/Thriller	1962		Movie	0.00	\N
3825	The Birds	317	Mystery/Horror/Thriller	1963		Movie	0.00	\N
3826	The Haunting	101	Mystery/Horror/Thriller	1963		Movie	0.00	\N
3827	Blood and Black Lace	595	Mystery/Horror/Thriller	1964		Movie	0.00	\N
3828	Repulsion	275	Mystery/Horror/Thriller	1965		Movie	0.00	\N
3829	Rosemarys Baby	275	Mystery/Horror/Thriller	1968		Movie	0.00	\N
3830	Night of the Living Dead	131	Mystery/Horror/Thriller	1968		Movie	0.00	\N
3831	Dont Look Now	293	Mystery/Horror/Thriller	1973		Movie	0.00	\N
3832	The Exorcist	136	Mystery/Horror/Thriller	1973		Movie	0.00	\N
3833	Black Christmas	320	Mystery/Horror/Thriller	1974		Movie	0.00	\N
3834	The Texas Chain Saw Massacre	14	Mystery/Horror/Thriller	1974		Movie	0.00	\N
3835	Jaws	200	Mystery/Horror/Thriller	1975		Movie	0.00	\N
3836	The Omen	321	Mystery/Horror/Thriller	1976		Movie	0.00	\N
3837	Carrie	322	Mystery/Horror/Thriller	1976		Movie	0.00	\N
3995	Dawn of the Dead	131	Mystery/Horror/Thriller	1978		Movie	0.00	\N
3996	Halloween	86	Mystery/Horror/Thriller	1978		Movie	0.00	\N
3997	Phantasm	323	Mystery/Horror/Thriller	1979		Movie	0.00	\N
3998	The Changeling	324	Mystery/Horror/Thriller	1980		Movie	0.00	\N
3999	Friday the 13th	325	Mystery/Horror/Thriller	1980		Movie	0.00	\N
4000	Possession	296	Mystery/Horror/Thriller	1981		Movie	0.00	\N
4001	An American Werewolf in London	326	Mystery/Horror/Thriller	1981		Movie	0.00	\N
4002	Creepshow	131	Mystery/Horror/Thriller	1982		Movie	0.00	\N
4003	Basket Case	327	Mystery/Horror/Thriller	1982		Movie	0.00	\N
4004	Poltergeist	14	Mystery/Horror/Thriller	1982		Movie	0.00	\N
4005	A Nightmare on Elm Street	328	Mystery/Horror/Thriller	1984		Movie	0.00	\N
4006	Fright Night	329	Mystery/Horror/Thriller	1985		Movie	0.00	\N
4007	The Return of the Living Dead	330	Mystery/Horror/Thriller	1985		Movie	0.00	\N
4008	Demons	331	Mystery/Horror/Thriller	1985		Movie	0.00	\N
4009	Re-Animator	332	Mystery/Horror/Thriller	1985		Movie	0.00	\N
4010	The Hitcher	333	Mystery/Horror/Thriller	1986		Movie	0.00	\N
4011	Henry: Portrait of a Serial Killer	334	Mystery/Horror/Thriller	1986		Movie	0.00	\N
4012	Evil Dead II	335	Mystery/Horror/Thriller	1987		Movie	0.00	\N
4013	The Lost Boys	162	Mystery/Horror/Thriller	1987		Movie	0.00	\N
4039	Hellraiser	155	Mystery/Horror/Thriller	1987		Movie	0.00	\N
4040	The Vanishing	336	Mystery/Horror/Thriller	1988		Movie	0.00	\N
4041	Child Play	329	Mystery/Horror/Thriller	1988		Movie	0.00	\N
4042	Pet Sematary	337	Mystery/Horror/Thriller	1989		Movie	0.00	\N
4043	Jacobs Ladder	154	Mystery/Horror/Thriller	1990		Movie	0.00	\N
4044	Misery	338	Mystery/Horror/Thriller	1990		Movie	0.00	\N
4045	Braindead	190	Mystery/Horror/Thriller	1992		Movie	0.00	\N
4046	Se7en	214	Mystery/Horror/Thriller	1995		Movie	0.00	\N
4047	Scream	328	Mystery/Horror/Thriller	1996		Movie	0.00	\N
4048	Ringu	339	Mystery/Horror/Thriller	1998		Movie	0.00	\N
4049	The Blair Witch Project	41	Mystery/Horror/Thriller	1999		Movie	0.00	\N
4050	The Sixth Sense	276	Mystery/Horror/Thriller	1999		Movie	0.00	\N
4051	Audition	340	Mystery/Horror/Thriller	1999		Movie	0.00	\N
4052	The Others	341	Mystery/Horror/Thriller	2001		Movie	0.00	\N
4053	28 Days Later	593	Mystery/Horror/Thriller	2002		Movie	0.00	\N
4054	Saw	342	Mystery/Horror/Thriller	2004		Movie	0.00	\N
4055	Shaun of the Dead	343	Mystery/Horror/Thriller	2004		Movie	0.00	\N
4056	The Descent	344	Mystery/Horror/Thriller	2005		Movie	0.00	\N
4057	The Devils Rejects	345	Mystery/Horror/Thriller	2005		Movie	0.00	\N
4058	Inside	42	Mystery/Horror/Thriller	2007		Movie	0.00	\N
4059	Rec	43	Mystery/Horror/Thriller	2007		Movie	0.00	\N
4060	Let the Right One In	346	Mystery/Horror/Thriller	2008		Movie	0.00	\N
4061	Oculus	347	Mystery/Horror/Thriller	2013		Movie	0.00	\N
4062	The Conjuring	342	Mystery/Horror/Thriller	2013		Movie	0.00	\N
4320	Creep	348	Mystery/Horror/Thriller	2014		Movie	0.00	\N
4321	The Babadook	349	Mystery/Horror/Thriller	2014		Movie	0.00	\N
4322	The VVitch	142	Mystery/Horror/Thriller	2015		Movie	0.00	\N
4323	Get Out	350	Mystery/Horror/Thriller	2017		Movie	0.00	\N
4325	Hereditary	109	Mystery/Horror/Thriller	2018		Movie	0.00	\N
4326	Attack of the 50 Foot Woman	285	Mystery/Horror/Thriller	1958		Movie	0.00	\N
4327	Je t’aime, Je t’aime	290	Mystery/Horror/Thriller	1968		Movie	0.00	\N
4338	Conquest	352	Fantasy/Adventure	1983		Movie	0.00	\N
4339	The Beastmaster	323	Fantasy/Adventure	1982		Movie	0.00	\N
4340	Krull	353	Fantasy/Adventure	1983		Movie	0.00	\N
4341	Warrior Queen	354	Fantasy/Adventure	2009		Movie	0.00	\N
4342	Sorceress	355	Fantasy/Adventure	1982		Movie	0.00	\N
4343	Barbarian Queen	356	Fantasy/Adventure	1985		Movie	0.00	\N
4344	Hundra	357	Fantasy/Adventure	1983		Movie	0.00	\N
4345	Gor	358	Fantasy/Adventure	1987		Movie	0.00	\N
4346	Deathstalker	359	Fantasy/Adventure	1983		Movie	0.00	\N
4347	Red Sonja	180	Fantasy/Adventure	1985		Movie	0.00	\N
4348	Amazons	360	Fantasy/Adventure	1986		Movie	0.00	\N
4349	The Barbarians	361	Fantasy/Adventure	1987		Movie	0.00	\N
4350	Ladyhawke	321	Fantasy/Adventure	1985		Movie	0.00	\N
4351	Dragonslayer	83	Fantasy/Adventure	1981		Movie	0.00	\N
4352	Flesh + Blood	229	Dark Fantasy	1985		Movie	0.00	\N
4432	Road House	362	Action	1989		Movie	0.00	\N
4433	Unstoppable	363	Action	2010		Movie	0.00	\N
4434	Shaft	364	Action	1971		Movie	0.00	\N
4435	The Villainess	365	Action	2017		Movie	0.00	\N
4436	Highlander	366	Action/Fantasy	1986		Movie	0.00	\N
4437	Die Hard 2	367	Action	1990		Movie	0.00	\N
4438	National Treasure	368	Action	2004		Movie	0.00	\N
4439	The Protector	369	Action/Martial Arts	2005		Movie	0.00	\N
4440	Revenge	115	Action	2017		Movie	0.00	\N
4441	El Mariachi	370	Action	1992		Movie	0.00	\N
4442	A Touch of Zen	371	Action/Martial Arts	1971		Movie	0.00	\N
4443	Top Gun	363	Action	1986		Movie	0.00	\N
4444	Con Air	372	Action	1997		Movie	0.00	\N
4445	The Expendables 2	372	Action	2012		Movie	0.00	\N
4446	The Mummy	373	Action/Fantasy	1999		Movie	0.00	\N
4447	Mr. & Mrs. Smith	305	Action	2005		Movie	0.00	\N
4448	Rush Hour	374	Action	1998		Movie	0.00	\N
4449	The Equalizer	375	Action	2014		Movie	0.00	\N
4450	Captain America: Civil War	44	Action/Superhero	2016		Movie	0.00	\N
4451	Air Force One	12	Action	1997		Movie	0.00	\N
4452	Bloodsport	376	Action/Martial Arts	1988		Movie	0.00	\N
4453	Blade	377	Action/Fantasy	1998		Movie	0.00	\N
4454	Bad Boys	378	Action	1995		Movie	0.00	\N
4455	Die Hard With a Vengeance	204	Action	1995		Movie	0.00	\N
4456	The Running Man	379	Action/Sci-Fi	1987		Movie	0.00	\N
4457	Code of Silence	380	Action	1985		Movie	0.00	\N
4458	Shoot Em Up	381	Action	2007		Movie	0.00	\N
4459	Crank	45	Action	2006		Movie	0.00	\N
4460	Machete	370	Action	2010		Movie	0.00	\N
4461	Batman	382	Action/Superhero	1989		Movie	0.00	\N
4462	Under Siege	380	Action	1992		Movie	0.00	\N
4463	Independence Day	298	Action/Sci-Fi	1996		Movie	0.00	\N
4464	Bullitt	353	Action	1968		Movie	0.00	\N
4465	Wanted	383	Action	2008		Movie	0.00	\N
4466	Superman: The Movie	321	Action/Superhero	1978		Movie	0.00	\N
4467	Ronin	287	Action/Thriller	1998		Movie	0.00	\N
4468	Cliffhanger	367	Action	1993		Movie	0.00	\N
4469	The Avengers	384	Action/Superhero	2012		Movie	0.00	\N
4668	Hot Fuzz	343	Action/Comedy	2007		Movie	0.00	\N
4669	The Warriors	385	Action	1979		Movie	0.00	\N
4670	Starship Troopers	229	Action/Sci-Fi	1997		Movie	0.00	\N
4671	Elite Squad 2	255	Action	2010		Movie	0.00	\N
4672	Point Break	386	Action	1991		Movie	0.00	\N
4673	The Long Kiss Goodnight	367	Action	1996		Movie	0.00	\N
4674	The Guest	166	Action/Thriller	2014		Movie	0.00	\N
4675	Taken	387	Action	2008		Movie	0.00	\N
4676	True Lies	198	Action	1994		Movie	0.00	\N
4677	Demolition Man	388	Action/Sci-Fi	1993		Movie	0.00	\N
4678	Hardcore Henry	389	Action	2015		Movie	0.00	\N
4679	Police Story	390	Action/Martial Arts	1985		Movie	0.00	\N
4680	Brotherhood of the Wolf	391	Action/Fantasy	2001		Movie	0.00	\N
4681	Kingsman: The Secret Service	392	Action	2014		Movie	0.00	\N
4682	Big Trouble in Little China	86	Action/Fantasy	1986		Movie	0.00	\N
4683	Atomic Blonde	393	Action	2017		Movie	0.00	\N
4684	Rumble in the Bronx	394	Action/Martial Arts	1995		Movie	0.00	\N
4685	District B13	387	Action	2004		Movie	0.00	\N
4686	Beverly Hills Cop	395	Action	1984		Movie	0.00	\N
4687	Ong-Bak: The Thai Warrior	369	Action/Martial Arts	2003		Movie	0.00	\N
4688	Collateral	197	Action/Thriller	2004		Movie	0.00	\N
4689	Iron Monkey	396	Action/Martial Arts	1993		Movie	0.00	\N
4690	Battle Royale	397	Action	2000		Movie	0.00	\N
4691	Spider-Man 2	335	Action/Superhero	2004		Movie	0.00	\N
4692	13 Assassins	340	Action/Samurai	2010		Movie	0.00	\N
4693	Full Contact	398	Action	1992		Movie	0.00	\N
4694	Indiana Jones and the Last Crusade	200	Action/Adventure	1989		Movie	0.00	\N
4695	Kung Fu Hustle	399	Action/Comedy	2004		Movie	0.00	\N
4696	A Better Tomorrow	400	Action	1986		Movie	0.00	\N
4697	Iron Man	401	Action/Superhero	2008		Movie	0.00	\N
4698	The Night Comes for Us	402	Action	2018		Movie	0.00	\N
4699	Logan	403	Action/Drama	2017		Movie	0.00	\N
4700	Goldfinger	404	Action/Spy	1964		Movie	0.00	\N
4701	Assault on Precinct 13	86	Action	1976		Movie	0.00	\N
4702	Wonder Woman	405	Action/Superhero	2017		Movie	0.00	\N
4703	The Chinese Connection	406	Action/Martial Arts	1972		Movie	0.00	\N
4704	Captain America: The Winter Soldier	44	Action/Superhero	2014		Movie	0.00	\N
5120	The French Connection	136	Action/Crime	1971		Movie	0.00	\N
5121	Furious 7	342	Action	2015		Movie	0.00	\N
5122	La Femme Nikita	91	Action/Thriller	1990		Movie	0.00	\N
5123	Supercop	394	Action/Martial Arts	1992		Movie	0.00	\N
5124	Dirty Harry	407	Action/Crime	1971		Movie	0.00	\N
5125	X2	408	Action/Superhero	2003		Movie	0.00	\N
5126	The Fugitive	380	Action/Thriller	1993		Movie	0.00	\N
5127	Braveheart	158	Action/War	1995		Movie	0.00	\N
5128	Avengers: Endgame	44	Action/Superhero	2019		Movie	0.00	\N
5129	Dredd	93	Action/Sci-Fi	2012		Movie	0.00	\N
5130	The Bourne Identity	305	Action/Thriller	2002		Movie	0.00	\N
5131	Ip Man	409	Action/Martial Arts	2008		Movie	0.00	\N
5132	Face/Off	400	Action	1997		Movie	0.00	\N
5133	To Live and Die in L.A.	136	Action/Crime	1985		Movie	0.00	\N
5134	Mission: Impossible - Ghost Protocol	410	Action	2011		Movie	0.00	\N
5135	Fast Five	411	Action	2011		Movie	0.00	\N
5136	Lethal Weapon	321	Action	1987		Movie	0.00	\N
5137	The Rock	378	Action	1996		Movie	0.00	\N
5138	John Wick: Chapter 2	412	Action	2017		Movie	0.00	\N
5139	Casino Royale	413	Action/Spy	2006		Movie	0.00	\N
5140	Baby Driver	343	Action	2017		Movie	0.00	\N
5141	Fist of Legend	414	Action/Martial Arts	1994		Movie	0.00	\N
5142	The Killer	400	Action	1989		Movie	0.00	\N
5143	The Raid 2	415	Action/Martial Arts	2014		Movie	0.00	\N
5144	Enter the Dragon	416	Action/Martial Arts	1973		Movie	0.00	\N
5145	Commando	417	Action	1985		Movie	0.00	\N
5146	First Blood	418	Action	1982		Movie	0.00	\N
5147	Mission: Impossible - Rogue Nation	168	Action	2015		Movie	0.00	\N
5148	Kill Bill: Vol. 1	196	Action	2003		Movie	0.00	\N
5149	The Professional	91	Action/Thriller	1994		Movie	0.00	\N
5150	Speed	419	Action	1994		Movie	0.00	\N
5151	Drunken Master II	420	Action/Martial Arts	1994		Movie	0.00	\N
5152	John Wick	412	Action	2014		Movie	0.00	\N
5153	Crouching Tiger, Hidden Dragon	421	Action/Fantasy	2000		Movie	0.00	\N
5154	The Bourne Ultimatum	422	Action	2007		Movie	0.00	\N
5155	Mad Max 2: The Road Warrior	125	Action	1981		Movie	0.00	\N
5235	The Raid: Redemption	415	Action/Martial Arts	2011		Movie	0.00	\N
5236	Mission: Impossible - Fallout	168	Action	2018		Movie	0.00	\N
5237	Raiders of the Lost Ark	200	Action/Adventure	1981		Movie	0.00	\N
5238	Hard-Boiled	400	Action	1992		Movie	0.00	\N
5393	1408	423	Mystery/Horror/Thriller	2007		Movie	0.00	\N
5394	The Crazies	424	Mystery/Horror/Thriller	2010		Movie	0.00	\N
5395	Eraser	84	Action/Thriller	1996		Movie	0.00	\N
5396	Triangle	425	Mystery/Horror/Thriller	2009		Movie	0.00	\N
5397	Cube	426	Mystery/Horror/Thriller	1997		Movie	0.00	\N
5398	Trick or Treat	427	Mystery/Horror/Thriller	1986		Movie	0.00	\N
5399	Isolation	428	Mystery/Horror/Thriller	2005		Movie	0.00	\N
5400	The Objective	8	Mystery/Horror/Thriller	2008		Movie	0.00	\N
5401	Session 9	429	Mystery/Horror/Thriller	2001		Movie	0.00	\N
5402	Lake Mungo	430	Mystery/Horror/Thriller	2008		Movie	0.00	\N
5403	Day of the Dead	131	Mystery/Horror/Thriller	1985		Movie	0.00	\N
5404	Dead or Alive	340	Action/Thriller	1999		Movie	0.00	\N
5405	Drag Me to Hell	335	Mystery/Horror/Thriller	2009		Movie	0.00	\N
5406	The Last House on the Left	328	Mystery/Horror/Thriller	1972		Movie	0.00	\N
5407	Open Water	431	Mystery/Horror/Thriller	2003		Movie	0.00	\N
5408	Dead Ringers	102	Mystery/Horror/Thriller	1988		Movie	0.00	\N
5409	The Fly	102	Sci-Fi/Horror	1986		Movie	0.00	\N
5410	May	432	Mystery/Horror/Thriller	2002		Movie	0.00	\N
6337	Room 1408	423	Mystery/Horror/Thriller	2007		Movie	0.00	\N
6338	Fragile	433	Mystery/Horror/Thriller	2005		Movie	0.00	\N
6339	Miracle Mile	434	Mystery/Horror/Thriller	1988		Movie	0.00	\N
6340	Paranormal Activity	435	Mystery/Horror/Thriller	2007		Movie	0.00	\N
6341	Teeth	436	Mystery/Horror/Thriller	2007		Movie	0.00	\N
6342	The Mist	235	Mystery/Horror/Thriller	2007		Movie	0.00	\N
6343	Pontypool	437	Mystery/Horror/Thriller	2008		Movie	0.00	\N
6344	The Brood	102	Mystery/Horror/Thriller	1979		Movie	0.00	\N
6345	Dog Soldiers	344	Mystery/Horror/Thriller	2002		Movie	0.00	\N
6346	Ginger Snaps	438	Mystery/Horror/Thriller	2000		Movie	0.00	\N
6347	Eden Lake	116	Mystery/Horror/Thriller	2008		Movie	0.00	\N
6348	Near Dark	386	Mystery/Horror/Thriller	1987		Movie	0.00	\N
7317	Trick Em Treat	439	Mystery/Horror/Thriller	2007		Movie	0.00	\N
7318	The Devil’s Rejects	345	Mystery/Horror/Thriller	2005		Movie	0.00	\N
7319	Eeden Lake	116	Mystery/Horror/Thriller	2008		Movie	0.00	\N
7525	Caltiki: The Immortal Monster	48	Sci-Fi	1959		Movie	0.00	\N
7526	Creature from the Black Lagoon	596	Sci-Fi	1954		Movie	0.00	\N
7527	Destination Moon	440	Sci-Fi	1950		Movie	0.00	\N
7528	Donovans Brain	441	Sci-Fi	1953		Movie	0.00	\N
7529	Half Human	442	Sci-Fi	1955		Movie	0.00	\N
7530	I Married a Monster from Outer Space	443	Sci-Fi	1958		Movie	0.00	\N
7531	I Was a Teenage Werewolf	444	Sci-Fi	1957		Movie	0.00	\N
7532	Invaders from Mars	445	Sci-Fi	1953		Movie	0.00	\N
7533	Island of Terror	446	Sci-Fi	1966		Movie	0.00	\N
7534	It! The Terror from Beyond Space	447	Sci-Fi	1958		Movie	0.00	\N
7535	Journey to the Center of the Earth	448	Sci-Fi	1959		Movie	0.00	\N
7536	Night of the Demon	153	Sci-Fi	1957		Movie	0.00	\N
7537	On the Beach	449	Sci-Fi	1959		Movie	0.00	\N
7538	Plan 9 from Outer Space	450	Sci-Fi	1959		Movie	0.00	\N
7539	Planet of the Vampires	595	Sci-Fi	1965		Movie	0.00	\N
7540	Red Planet Mars	451	Sci-Fi	1952		Movie	0.00	\N
7541	Robot Monster	452	Sci-Fi	1953		Movie	0.00	\N
7542	Tarantula	596	Sci-Fi	1955		Movie	0.00	\N
7543	The Beast from 20,000 Fathoms	453	Sci-Fi	1953		Movie	0.00	\N
7544	The Black Scorpion	49	Sci-Fi	1957		Movie	0.00	\N
7545	The Brain That Wouldnt Die	454	Sci-Fi	1962		Movie	0.00	\N
7546	The Day of the Triffids	50	Sci-Fi	1962		Movie	0.00	\N
7547	The Day the Earth Caught Fire	455	Sci-Fi	1961		Movie	0.00	\N
7548	The H-Man	82	Sci-Fi	1958		Movie	0.00	\N
7549	The Human Vapor	82	Sci-Fi	1960		Movie	0.00	\N
7550	The Incredible Shrinking Man	596	Sci-Fi	1957		Movie	0.00	\N
7551	The Last Man on Earth	51	Sci-Fi	1964		Movie	0.00	\N
7552	The Man From Planet X	456	Sci-Fi	1951		Movie	0.00	\N
7553	The Mole People	457	Sci-Fi	1956		Movie	0.00	\N
7554	The Secret of the Telegian	458	Sci-Fi	1960		Movie	0.00	\N
7555	The Time Machine	459	Sci-Fi	1960		Movie	0.00	\N
7556	The War of the Worlds	286	Sci-Fi	1953		Movie	0.00	\N
7557	The World, the Flesh and the Devil	460	Sci-Fi	1959		Movie	0.00	\N
7558	Them!	461	Sci-Fi	1954		Movie	0.00	\N
7559	This Island Earth	52	Sci-Fi	1955		Movie	0.00	\N
7560	Village of the Damned	462	Sci-Fi	1960		Movie	0.00	\N
7561	When Worlds Collide	463	Sci-Fi	1951		Movie	0.00	\N
7562	X: The Man with the X-Ray Eyes	464	Sci-Fi	1963		Movie	0.00	\N
7563	Frankenstein (2025)	465	Horror/Thriller	2025		Movie	0.00	\N
7564	Predator: Badlands	312	Sci-Fi/Action	2025		Movie	0.00	\N
7565	Dracula: A Love Tale	91	Vampires/Horror/Romance	2025		Movie	0.00	\N
7566	Alien: Prometheus	161	Sci-Fi/Thriller/Slasher	2012		Movie	0.00	\N
7567	Hellraiser (2022)	466	Horror/Thriller/Slasher	2022		Movie	0.00	\N
7569	Alien: Ressurection	467	Sci-Fi/Thriller/Slasher	1997		Movie	0.00	\N
7570	Alien: Covenant	161	Sci-Fi/Thriller/Slaher	2017		Movie	0.00	\N
7571	Alien: Romulus	468	Sci-Fi/Thriller/Slaher	2024		Movie	0.00	\N
7572	Alien³	214	Sci-Fi/Thriller/Slaher	1992		Movie	0.00	\N
7579	Pirates Of Silicon Valley	469	Drama/Biography/History	1999	History of Apple and Microsoft.	Movie	1.35	\N
7580	Sleepwalkers	470	Fantasy/Horror/Monster Horror/Cosmic Horror	1992	A mother-and-son team of shapeshifters move to a small town to seek out a young virgin to feed on.	Movie	1.29	\N
7581	The Imitation Game	471	War/Period Drama/Psychological Drama/Tragedy/Biography/Drama	2014	During World War II, the English mathematical genius Alan Turing tries to crack the German Enigma code with help from fellow mathematicians while attempting to come to terms with his troubled private life.	Movie	0.00	\N
7591	Predator II	472	Sci-Fi/Action/Slasher/Thriller	1997	Los Angeles police hunt an alien creature in 1997.	Movie	0.00	\N
7592	Predators (Predator III)	473	Sci-Fi/Action/Slasher/Thriller	2010	A group of elite warriors parachute into an unfamiliar jungle and are hunted by members of a merciless alien race.	Movie	0.00	\N
7593	Sinners	212	Horror/Vampire/Slasher/Folk Drama/Period Drama	2025	Trying to leave their troubled lives behind, twin brothers return to their hometown to start again, only to discover that an even greater evil is waiting to welcome them back.	Movie	0.00	\N
7598	Aliens Expanded	474	Documentary	2024	An in-depth and innovative documentary that explores the story behind James Camerons beloved sci-fi epic Aliens (1986) and its incredible impact.	Documentary	0.00	\N
7599	The Predator	475	Sci-Fi/Action/Adventure	2018	When a young boy accidentally triggers the universes most lethal hunters return to Earth, only a ragtag crew of ex-soldiers and a disgruntled scientist can prevent the end of the human race.	Movie	0.00	\N
7600	Alien vs Predator	476	Sci-Fi/Adventure/Action	2004	During an archaeological expedition on Bouvetøya Island in Antarctica, a team of archaeologists and other scientists find themselves caught up in a battle between the two legends. Soon, the team realize that only one species can win.	Movie	0.00	\N
7601	Alien vs Predator: Requiem	53	Sci-Fi/Adventure/Action	2007	Warring Alien and Predator races descend on a rural Colorado town, where unsuspecting residents must band together for any chance of survival.	Movie	0.00	\N
7602	Jurassic World: Rebirth	306	Sci-Fi/Adventure/Action/Dinosaur	2025	Five years post-Jurassic World: Dominion (2022), an expedition braves isolated equatorial regions to extract DNA from three massive prehistoric creatures for a groundbreaking medical breakthrough.	Movie	0.00	\N
7603	Deathstalker (2025)	477	Fantasy/Adventure/Dark Fantasy	2025	A remake of the cult classic 1983 sword and sorcery film.	Movie	0.00	\N
7604	One Batle After Another	192	Action/Crime/Politics/Dark Comedy/Drama	2025	When their evil enemy resurfaces after 16 years, a group of ex-revolutionaries reunite to rescue the daughter of one of their own.	Movie	0.00	\N
7605	Oblivion	249	Sci-Fi	2013	A strangers arrival triggers one mans battle to save mankind.	Movie	2.40	\N
7606	The Relic	137	Sci-Fi/Horror/Thriller/Slasher	1997	A homicide detective and an anthropologist try to destroy a South American lizard-like God, whos on a people eating rampage in a Chicago museum.	Movie	1.50	\N
7872	Cat People	153	Folk Horror/Horror/Thriller	1942	An American man marries a Serbian immigrant who fears that she will turn into the cat person of her homelands fables if they are intimate together.	Movie	1.13	\N
7873	Day of the warrior	598	Fantasy/Martial Arts/Spy/Action/Adventure	1996	A former CIA agent has breached the Agencys computer database. With his criminal influence extending everywhere and classified documents in his grasp, the forces operatives are at his mercy. What will it take to end the Warriors days?	Movie	1.36	\N
7874	Day of Night	28	Fantasy/Drama/Horror/Mystery	1945	An architect, visiting an English country house, realizes the other guests are familiar from his recurring nightmare. When they share their tales of the supernatural, he is filled with a growing dread.	Movie	1.45	\N
7875	Evil Dead III (Army of Darkness)	335	Fantasy/Horror/Comedy	1992	A man is accidentally transported to 1300 A.D., where he must battle an army of the dead and retrieve the Necronomicon so he can return home.	Movie	1.21	\N
7876	Evil Dead IV	468	Horror	2013	Five friends head to a remote cabin, where the discovery of a Book of the Dead leads them to unwittingly summon up demons living in the nearby woods.	Movie	1.31	\N
7877	Evil Dead: Rise (Evil Dead V)	599	Horror	2023	A twisted tale of two estranged sisters whose reunion is cut short by the rise of flesh-possessing demons, thrusting them into a primal battle for survival as they face the most nightmarish version of family imaginable.	Movie	1.37	\N
7878	F1 The Movie	600	Action/Drama	2025	A film about the high-octane world of Formula 1 racing.	Movie	2.10	\N
7879	Godzilla	82	Horror/Sci-Fi	1954	American nuclear weapons testing results in the creation of a seemingly unstoppable, dinosaur-like beast.	Movie	1.36	\N
7880	Hellbound: Hellraiser II	155	Horror	1988	Kirsty is brought to an institution after the events of the first film, where the occult-obsessive head doctor resurrects Julia and unleashes the Cenobites once again.	Movie	1.37	\N
7881	I Am Joe Frazier	601	Biography/Drama/Sport	2025	The story of heavyweight boxing champion Joe Frazier.	Movie	2.05	\N
7882	Soylent Green	180	Crime/Drama/Mystery/Sci-Fi/Thriller	1973	In an overpopulated and starving New York City of the future, a police detective investigates the murder of a wealthy executive.	Movie	1.37	\N
7883	The Warrior and the Sorceress	352	Fantasy/Sci-Fi	1984	A wandering warrior arrives in a city ruled by an evil queen and held in the grip of a terrible monster.	Movie	1.21	\N
7884	The Animatrix	602	Animation/Action/Drama/Sci-Fi	2003	A collection of nine short anime films set in the world of The Matrix.	Movie	1.42	\N
7885	The Black Cat	603	Crime/Horror/Mystery	1934	A honeymooning couple encounters a satanic priest in Hungary.	Movie	1.05	\N
7886	The Divide	604	Drama/Horror/Sci-Fi/Thriller	2011	Survivors of a nuclear attack are grouped together for days in the basement of their apartment building, where fear and dwindling supplies wear away at their dynamic.	Movie	1.57	\N
7887	The Evil Dead (Evil Dead I)	335	Horror	1981	Five friends travel to a cabin in the woods, where they unknowingly release flesh-possessing demons.	Movie	1.25	\N
7888	The Occupant	605	Drama/Mystery/Thriller/Sci-Fi	2025	A woman moves into a new apartment and begins to suspect her neighbor is not who he seems.	Movie	1.40	\N
7889	The Ritual	466	Adventure/Drama/Horror/Mystery/Thriller	2017	A group of college friends reunite for a trip to the forest, but encounter a menacing presence in the woods that is stalking them.	Movie	1.34	\N
7890	The Wolf Man	150	Drama/Horror	1941	A practical man returns to his homeland, is attacked by a creature of folklore, and infected with a horrific disease his disciplined mind tells him can not possibly exist.	Movie	1.10	\N
7891	Threads	606	Drama/Horror/Sci-Fi/War	1984	The effects of a nuclear holocaust on the working-class city of Sheffield, England, and the eventual descent of its citizens into utter barbarism.	Movie	1.50	\N
7892	Vampyr	607	Fantasy/Horror	1932	A student of the occult encounters supernatural haunts and local evildoers in a village outside of Paris.	Movie	1.13	\N
4324	It	351	Mystery/Horror/Thriller	2017		Movie	0.00	\N
\.


--
-- TOC entry 5077 (class 0 OID 16562)
-- Dependencies: 229
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, user_name, email) FROM stdin;
1	Vin Martins	vinmartins@localcinema.com
2	Peewee Brothers	peeweebrothers@localcinema.com
3	João Da Silva	joaodasilva@localcinema.com
4	Maria Da Silva	mariadasilva@localcinema.com
5	Lucas do Refúgio cult	lucasdorefugiocult@localcinema.com
\.


--
-- TOC entry 5079 (class 0 OID 16571)
-- Dependencies: 231
-- Data for Name: watchlist; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.watchlist (id, title_id) FROM stdin;
66	116
74	127
6	129
56	130
73	169
70	226
58	3817
61	3818
7	4012
55	4325
75	7559
59	7579
69	7581
5	7873
8	7875
78	7876
23	7879
57	7881
62	7883
68	7887
71	7888
76	7891
77	7892
\.


--
-- TOC entry 5086 (class 0 OID 0)
-- Dependencies: 220
-- Name: directors_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.directors_id_seq', 1, false);


--
-- TOC entry 5087 (class 0 OID 0)
-- Dependencies: 222
-- Name: genres_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.genres_id_seq', 1, false);


--
-- TOC entry 5088 (class 0 OID 0)
-- Dependencies: 224
-- Name: haswatched_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.haswatched_id_seq', 67, true);


--
-- TOC entry 5089 (class 0 OID 0)
-- Dependencies: 226
-- Name: series_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.series_id_seq', 1, false);


--
-- TOC entry 5090 (class 0 OID 0)
-- Dependencies: 228
-- Name: titles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.titles_id_seq', 1, false);


--
-- TOC entry 5091 (class 0 OID 0)
-- Dependencies: 230
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- TOC entry 5092 (class 0 OID 0)
-- Dependencies: 232
-- Name: watchlist_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.watchlist_id_seq', 1, false);


--
-- TOC entry 4895 (class 2606 OID 16577)
-- Name: directors directors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.directors
    ADD CONSTRAINT directors_pkey PRIMARY KEY (id);


--
-- TOC entry 4897 (class 2606 OID 16579)
-- Name: genres genres_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.genres
    ADD CONSTRAINT genres_pkey PRIMARY KEY (id);


--
-- TOC entry 4899 (class 2606 OID 16581)
-- Name: haswatched haswatched_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.haswatched
    ADD CONSTRAINT haswatched_pkey PRIMARY KEY (id);


--
-- TOC entry 4901 (class 2606 OID 16583)
-- Name: series series_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.series
    ADD CONSTRAINT series_pkey PRIMARY KEY (id);


--
-- TOC entry 4903 (class 2606 OID 16585)
-- Name: series series_series_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.series
    ADD CONSTRAINT series_series_name_key UNIQUE (series_name);


--
-- TOC entry 4905 (class 2606 OID 16587)
-- Name: titles titles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.titles
    ADD CONSTRAINT titles_pkey PRIMARY KEY (id);


--
-- TOC entry 4907 (class 2606 OID 16589)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 4909 (class 2606 OID 16591)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4911 (class 2606 OID 16593)
-- Name: users users_user_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_user_name_key UNIQUE (user_name);


--
-- TOC entry 4913 (class 2606 OID 16595)
-- Name: watchlist watchlist_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.watchlist
    ADD CONSTRAINT watchlist_pkey PRIMARY KEY (id);


--
-- TOC entry 4914 (class 2606 OID 16596)
-- Name: haswatched haswatched_series_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.haswatched
    ADD CONSTRAINT haswatched_series_id_fkey FOREIGN KEY (series_id) REFERENCES public.series(id);


--
-- TOC entry 4915 (class 2606 OID 16601)
-- Name: haswatched haswatched_title_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.haswatched
    ADD CONSTRAINT haswatched_title_id_fkey FOREIGN KEY (title_id) REFERENCES public.titles(id);


--
-- TOC entry 4916 (class 2606 OID 16606)
-- Name: haswatched haswatched_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.haswatched
    ADD CONSTRAINT haswatched_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4917 (class 2606 OID 16611)
-- Name: titles titles_director_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.titles
    ADD CONSTRAINT titles_director_id_fkey FOREIGN KEY (director_id) REFERENCES public.directors(id);


--
-- TOC entry 4918 (class 2606 OID 16616)
-- Name: titles titles_genres_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.titles
    ADD CONSTRAINT titles_genres_fkey FOREIGN KEY (genres) REFERENCES public.genres(id);


--
-- TOC entry 4919 (class 2606 OID 16621)
-- Name: watchlist watchlist_title_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.watchlist
    ADD CONSTRAINT watchlist_title_id_fkey FOREIGN KEY (title_id) REFERENCES public.titles(id);


-- Completed on 2026-02-18 16:39:07

--
-- PostgreSQL database dump complete
--

\unrestrict 3qIAl11L79Wc9JzeBlfpcBjyuSZqwrOUyaLZdarmYtEgageaMeHanwuPQ02XTZV

