--
-- PostgreSQL database dump
--

\restrict J1jIw9u4JITzJ0Qdb1r4htoDK4QEyeE45nqy17hBMX1AkeoQKGAQUZGKiG63958

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-04-02 10:54:58

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16388)
-- Name: directors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.directors (
    id integer NOT NULL,
    name character varying(255) DEFAULT NULL::character varying,
    featured_names character varying(255)
);


ALTER TABLE public.directors OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16395)
-- Name: directors_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.directors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.directors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16396)
-- Name: genres; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.genres (
    id integer NOT NULL,
    genre_name text,
    featured_genres character varying(255)
);


ALTER TABLE public.genres OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16402)
-- Name: genres_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.genres ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.genres_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16403)
-- Name: haswatched; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.haswatched (
    id integer NOT NULL,
    user_id integer,
    title_id integer,
    watch_date date NOT NULL,
    watch_count integer NOT NULL,
    user_comment text,
    user_rating numeric(3,1) DEFAULT NULL::numeric,
    series_id integer
);


ALTER TABLE public.haswatched OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16412)
-- Name: haswatched_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.haswatched ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.haswatched_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16413)
-- Name: series; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.series (
    id integer NOT NULL,
    series_name character varying(255) NOT NULL,
    creator character varying(255) NOT NULL,
    year_release smallint NOT NULL,
    genre_id integer NOT NULL
);


ALTER TABLE public.series OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16427)
-- Name: series_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.series ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.series_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16428)
-- Name: titles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.titles (
    id integer NOT NULL,
    name character varying(255) CONSTRAINT titles_title_not_null NOT NULL,
    director_id integer NOT NULL,
    year_release integer NOT NULL,
    category character varying(20) DEFAULT 'Movie'::character varying,
    runtime numeric(3,2),
    genre_id integer NOT NULL,
    CONSTRAINT titles_category_check CHECK (((category)::text = ANY (ARRAY[('Movie'::character varying)::text, ('Documentary'::character varying)::text, ('Animation'::character varying)::text])))
);


ALTER TABLE public.titles OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16440)
-- Name: titles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.titles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.titles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16441)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    user_name character varying(255) NOT NULL,
    email character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16449)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16450)
-- Name: watchlist; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.watchlist (
    id integer NOT NULL,
    title_id integer
);


ALTER TABLE public.watchlist OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16454)
-- Name: watchlist_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.watchlist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.watchlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5066 (class 0 OID 16388)
-- Dependencies: 219
-- Data for Name: directors; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.directors (id, name, featured_names) FROM stdin;
15	Ti West	\N
7	Eduardo Sánches	\N
8	Daniel Myrick	\N
11	Grégory Levasseur	\N
13	Abel Ferrara	\N
14	Tobe Hooper	\N
18	Jude S. Walko	\N
353	Peter Yates	\N
82	Ishirô Honda	\N
83	Matthew Robbins	\N
84	Chuck Russell	\N
85	Randal Kleiser	\N
86	John Carpenter	\N
87	Stewart Raffill	\N
88	Alex Cox	\N
89	Jack Sholder	\N
90	Terry Gilliam	\N
91	Luc Besson	\N
92	Scott Derrickson	\N
93	Pete Travis	\N
94	Steven Soderbergh	\N
95	Greg Berlanti	\N
96	James Gray	\N
97	Kurt Wimmer	\N
98	Wes Ball	\N
99	Sam Esmail	\N
100	Francis Ford Coppola	\N
101	Robert Wise	\N
102	David Cronenberg	\N
103	Chris Walas	\N
104	Fred Olen Ray	\N
105	George Nolfi	\N
106	Drew Hancock	\N
107	Bryan Bertino	\N
108	Paul McGuigan	\N
109	Ari Aster	\N
110	Chris Nash	\N
111	Ishana Shyamalan	\N
112	Susanne Bier	\N
113	OZ Perkins	\N
114	Natalie Erika James	\N
115	Coralie Fargeat	\N
116	James Watkins	\N
117	Alexandre Aja	\N
118	David F. Sandberg	\N
119	David Robert Mitchell	\N
120	John Erick Dowdle	\N
121	Anthony Cousins	\N
122	Michael Goi	\N
123	Philip Kaufman	\N
124	Christian Tafdrup	\N
125	George Miller	\N
126	Willian Wayler	\N
127	Danny Cannon	\N
128	Fernando Barreda Luna	\N
129	Adrian Țofei	\N
130	Adam Robitel	\N
131	George A. Romero	\N
132	Bobby Roe	\N
133	Rob Savage	\N
134	Benjamin Barfoot	\N
135	Andy Milligan	\N
136	William Friedkin	\N
137	Peter Hyams	\N
138	Zoë Kravitz	\N
139	Kyle Mooney	\N
140	James Whale	\N
141	William Castle	\N
142	Robert Eggers	\N
143	Boris Sagal	\N
144	Dario Argento	\N
145	Luca Guadagnino	\N
146	Kevin Smith	\N
147	Kiyoshi Kurosawa	\N
148	Parker Finn	\N
149	Leigh Whannell	\N
150	George Waggner	\N
151	Zach LipovskyAdam B. Stein	\N
152	André De Toth	\N
153	Jacques Tourneur	\N
154	Adrian Lyne	\N
155	Clive Barker	\N
156	Zach Cregger	\N
157	Michael Chaves	\N
158	Mel Gibson	\N
159	Matthew Holmes	\N
160	Kelly Marcel	\N
161	Ridley Scott	\N
162	Joel Schumacher	\N
163	Kevin Macdonald	\N
164	J.C. Chandor	\N
165	Justin Routt	\N
166	Adam Wingard	\N
167	Christopher Nolan	\N
168	Christopher McQuarrie	\N
169	Clint Eastwood	\N
170	Rodrigo Cortés	\N
171	Barry Levinson	\N
172	Richard Gray	\N
173	Lars von Trier	\N
174	Nicholas Hytner	\N
175	Aaron Schimberg	\N
176	Kenji Kamiyama	\N
177	Ralph Bakshi	\N
178	Stephen Presley	\N
179	Henrik Burman	\N
180	Richard Fleischer	\N
181	John Milius	\N
182	Albert Pyun	\N
183	Sergey Bondarchuk	\N
184	Ron Howard	\N
185	Alex Proyas	\N
186	Rupert Sanders	\N
17		Bryan M. Ferguson, Casper Kelly, R.H. Norman
19	\N	John Bruno, John Halas, Julian Harris
20	\N	Michael Coldewey, Michel Lemire
21	\N	Christian Nyby, Howard Hawks
22	\N	Banjong Pisanthanakun, Parkpoom Wongpoom
23	\N	David Amito, Michael Laicini
25	\N	Colin Minihan, Stuart Ortiz
26	\N	Karl Freund, Tod Browning
27	\N	Bryan Woods, Scott Beck
28	\N	Alberto Cavalcanti, Basil Dearden, Charles Crichton
29	\N	Danny Philippou, Michael Philippou
30	\N	Frank Oz, Jim Henson
31	\N	Danny Boyle, Loveleen Tandan
32	\N	Ethan Coen, Joel
33	\N	Lana, Lilly Wachowski
34	\N	Ethan Coen, Joel
35	\N	Fernando Meirelles, Kátia Lund
36	\N	Ethan Coen, Joel
37	\N	Aaron Moorhead, Justin Benson
38	\N	Michael, Peter Spierig
39	\N	Chris Caldwell, Zeek Earl
40	\N	Aaron Moorhead, Justin Benson
41	\N	Daniel Myrick, Eduardo Sánchez
42	\N	Alexandre Bustillo, Julien Maury
43	\N	Jaume Balagueró, Paco Plaza
44	\N	Anthony, Joe Russo
45	\N	Neveldine, Taylor
46	\N	Anthony, Joe Russo
47	\N	Anthony, Joe Russo
48	\N	Mario Bava, Riccardo Freda
49	\N	Edward Ludwig, Izvestiy Antonovich
50	\N	Freddie Francis, Steve Sekely
51	\N	Sidney Salkow, Ubaldo Ragona
52	\N	Jack Arnold, Joseph M. Newman
53	\N	Colin Strause, Greg Strause
187	Denis Villeneuve	\N
188	Martin Scorsese	\N
189	Stanley Kubrick	\N
190	Peter Jackson	\N
191	Nicolas Winding Refn	\N
192	Paul Thomas Anderson	\N
193	David Lynch	\N
194	Sergio Leone	\N
195	David Lean	\N
196	Quentin Tarantino	\N
197	Michael Mann	\N
198	James Cameron	\N
199	Mary Harron	\N
200	Steven Spielberg	\N
201	Andrei Tarkovsky	\N
202	George Lucas	\N
203	Miloš Forman	\N
204	John McTiernan	\N
205	Damien Chazelle	\N
206	Andrew Dominik	\N
207	Park Chan-wook	\N
208	Akira Kurosawa	\N
209	Zack Snyder	\N
210	Hideaki Anno	\N
211	Irvin Kershner	\N
212	Ryan Coogler	\N
213	Frank Capra	\N
214	David Fincher	\N
215	Michel Gondry	\N
216	Masaki Kobayashi	\N
217	Dan Gilroy	\N
218	Brian Levant	\N
219	Sion Sono	\N
220	Peter Weir	\N
221	Sidney Lumet	\N
222	Ingmar Bergman	\N
223	Charlie Kaufman	\N
224	Bong Joon-ho	\N
225	Terrence Malick	\N
226	Oliver Stone	\N
227	Katsuhiro Otomo	\N
228	Martin McDonagh	\N
229	Paul Verhoeven	\N
230	John Boorman	\N
231	Jonathan Glazer	\N
232	Elem Klimov	\N
233	Sofia Coppola	\N
234	Wong Kar-wai	\N
235	Frank Darabont	\N
236	Jonathan Demme	\N
237	Andrew Niccol	\N
238	Fred M. Wilcox	\N
239	Shane Carruth	\N
240	Alfonso Cuarón	\N
241	Paul W. S. Anderson	\N
242	Neill Blomkamp	\N
243	Sebastián Cordero	\N
244	Duncan Jones	\N
245	Alex Garland	\N
246	Douglas Trumbull	\N
247	Nicholas Meyer	\N
248	Franklin J. Schaffner	\N
249	Joseph Kosinski	\N
250	Fritz Lang	\N
251	Andrew Stanton	\N
252	Mamoru Oshii	\N
253	Spike Jonze	\N
254	Robert Benton	\N
255	José Padilha	\N
256	Thomas Vinterberg	\N
257	Steve McQueen	\N
258	Jean-Marc Vallée	\N
259	Lee Jang-soo	\N
260	Darius Marder	\N
261	Heitor Dhalia	\N
262	Jean-Pierre Melville	\N
263	Penny Marshall	\N
264	Kevin Reynolds	\N
265	Michael Cimino	\N
266	Roland Joffé	\N
267	Max Barbakow	\N
268	Lexi Alexander	\N
269	John Badham	\N
270	John Ford	\N
271	John G. Avildsen	\N
272	John Hillcoat	\N
273	Mike Nichols	\N
274	Gavin O Connor	\N
275	Roman Polanski	\N
276	M. Night Shyamalan	\N
277	Matt Reeves	\N
278	Krzysztof Kieślowski	\N
279	Jeff Schaffer	\N
280	Robin Hardy	\N
281	Kenneth Lonergan	\N
282	Robert Zemeckis	\N
283	Cameron Crowe	\N
284	Sean Penn	\N
285	Nathan H. Juran	\N
286	Byron Haskin	\N
287	John Frankenheimer	\N
288	Hiroshi Teshigahara	\N
289	Roger Vadim	\N
290	Alain Resnais	\N
291	Michael Crichton	\N
292	Michael Anderson	\N
293	Nicolas Roeg	\N
294	Mike Hodges	\N
295	Steven Lisberger	\N
296	Andrzej Żuławski	\N
297	Richard Stanley	\N
298	Roland Emmerich	\N
299	Dean Parisot	\N
300	Richard Kelly	\N
301	Richard Linklater	\N
302	Satoshi Kon	\N
303	Mark Romanek	\N
304	Rian Johnson	\N
305	Doug Liman	\N
306	Gareth Edwards	\N
307	John Krasinski	\N
308	Claire Denis	\N
309	Andrew Patterson	\N
310	Brandon Cronenberg	\N
311	Neasa Hardiman	\N
312	Dan Trachtenberg	\N
313	Henri-Georges Clouzot	\N
314	Charles Laughton	\N
315	Georges Franju	\N
316	Michael Powell	\N
317	Alfred Hitchcock	\N
318	Jack Clayton	\N
319	Robert Aldrich	\N
320	Bob Clark	\N
321	Richard Donner	\N
322	Brian De Palma	\N
323	Don Coscarelli	\N
324	Peter Medak	\N
325	Sean S. Cunningham	\N
326	John Landis	\N
327	Frank Henenlotter	\N
328	Wes Craven	\N
329	Tom Holland	\N
330	Dan O Bannon	\N
331	Lamberto Bava	\N
332	Stuart Gordon	\N
333	Robert Harmon	\N
334	John McNaughton	\N
335	Sam Raimi	\N
336	George Sluizer	\N
337	Mary Lambert	\N
338	Rob Reiner	\N
339	Hideo Nakata	\N
340	Takashi Miike	\N
341	Alejandro Amenábar	\N
342	James Wan	\N
343	Edgar Wright	\N
344	Neil Marshall	\N
345	Rob Zombie	\N
346	Tomas Alfredson	\N
347	Mike Flanagan	\N
348	Patrick Brice	\N
349	Jennifer Kent	\N
350	Jordan Peele	\N
351	Andy Muschietti	\N
352	John C. Broderick	\N
354	Ernesto Díaz Espinoza	\N
355	Jack Hill	\N
356	Hugh Parks	\N
357	Matt Cimber	\N
358	Ernest Day	\N
359	Doug Lefler	\N
360	Joe Mari Avellana	\N
361	Tito Davison	\N
362	Rowdy Herrington	\N
363	Tony Scott	\N
364	Gordon Parks	\N
365	Jung Byung-gil	\N
366	Russell Mulcahy	\N
367	Renny Harlin	\N
368	Jon Turteltaub	\N
369	Prachya Pinkaew	\N
370	Robert Rodriguez	\N
371	King Hu	\N
372	Simon West	\N
373	Stephen Sommers	\N
374	Brett Ratner	\N
375	Antoine Fuqua	\N
376	Newt Arnold	\N
377	Stephen Norrington	\N
378	Michael Bay	\N
379	Paul Michael Glaser	\N
380	Andrew Davis	\N
381	Michael Davis	\N
382	Tim Burton	\N
383	Timur Bekmambetov	\N
384	Joss Whedon	\N
385	Walter Hill	\N
386	Kathryn Bigelow	\N
387	Pierre Morel	\N
388	Marco Brambilla	\N
389	Ilya Naishuller	\N
390	Jackie Chan	\N
391	Christophe Gans	\N
392	Matthew Vaughn	\N
393	David Leitch	\N
394	Stanley Tong	\N
395	Martin Brest	\N
396	Yuen Woo-ping	\N
397	Kinji Fukasaku	\N
398	Ringo Lam	\N
399	Stephen Chow	\N
400	John Woo	\N
401	Jon Favreau	\N
402	Timo Tjahjanto	\N
403	James Mangold	\N
404	Guy Hamilton	\N
405	Patty Jenkins	\N
406	Lo Wei	\N
407	Don Siegel	\N
408	Bryan Singer	\N
409	Wilson Yip	\N
410	Brad Bird	\N
411	Justin Lin	\N
412	Chad Stahelski	\N
413	Martin Campbell	\N
414	Gordon Chan	\N
415	Gareth Evans	\N
416	Robert Clouse	\N
417	Mark L. Lester	\N
418	Ted Kotcheff	\N
419	Jan de Bont	\N
420	Lau Kar-leung	\N
421	Ang Lee	\N
422	Paul Greengrass	\N
423	Mikael Håfström	\N
424	Breck Eisner	\N
425	Christopher Smith	\N
426	Vincenzo Natali	\N
427	Charles Martin Smith	\N
428	Bryn Higgins	\N
429	Brad Anderson	\N
430	Joel Anderson	\N
431	Chris Kentis	\N
432	Lucky McKee	\N
433	Andrew Douglas	\N
434	Steve De Jarnatt	\N
435	Oren Peli	\N
436	Mitchell Lichtenstein	\N
437	Bruce McDonald	\N
438	John Fawcett	\N
439	Michael Dougherty	\N
440	Irwin Allen	\N
441	Felix E. Feist	\N
442	Tetsuo Yoshida	\N
443	Gene Fowler Jr.	\N
444	Fred F. Sears	\N
445	William Cameron Menzies	\N
446	Terence Fisher	\N
447	Edward L. Cahn	\N
448	Henry Levin	\N
449	Stanley Kramer	\N
450	Ed Wood	\N
451	Harry Horner	\N
452	Phil Tucker	\N
453	Eugene Lourié	\N
454	Joseph Green	\N
455	Val Guest	\N
456	Edwin L. Marin	\N
457	Virgil W. Vogel	\N
458	Jun Fukuda	\N
459	George Pal	\N
460	Ranald MacDougall	\N
461	Gordon Douglas	\N
462	Wolf Rilla	\N
463	Rudolph Maté	\N
464	Roger Corman	\N
465	Guillermo del Toro	\N
466	David Bruckner	\N
467	Jean-Pierre Jeunet	\N
468	Fede Alvarez	\N
469	Martyn Burke	\N
470	Mick Garris	\N
471	Morten Tyldum	\N
472	Stephen Hopkins	\N
473	Nimród Antal	\N
474	Ian Nathan	\N
475	Shane Black	\N
476	Paul W.S. Anderson	\N
477	Steven Kostanski	\N
593	Danny Boyle	\N
594	Tod Browning	\N
595	Mario Bava	\N
596	Jack Arnold	\N
597	Joseph Kosinski	\N
598	Andy Sidaris	\N
599	Lee Cronin	\N
600	Joseph Kosinski	\N
601	Pete McCormack	\N
603	Edgar G. Ulmer	\N
604	Xavier Gens	\N
605	Hugo Keijzer	\N
606	Mick Jackson	\N
607	Carl Theodor Dreyer	\N
12	Wolfgang Petersen	\N
1	Nia DaCosta	\N
16		Jay Cheel, Jordan Downey, Christian Long, Justin Long, Justin Martinez, Virat Pal, Kate Siegel
24	\N	Cristie Whiles, Fred Vogel, Jerami Cruise, Killjoy, Michael Todd Schneider
602		Peter Chung, Andrew R. Jones, Yoshiaki Kawajiri
2	Bart Layton	\N
3	\N	Megumi Inman, James Jones
4	Andrew Stanton	\N
5	Adam Davidson	\N
6	Adam MacDonald	\N
9	Gore Verbinski	\N
10	Kevin Williamson	\N
\.


--
-- TOC entry 5068 (class 0 OID 16396)
-- Dependencies: 221
-- Data for Name: genres; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.genres (id, genre_name, featured_genres) FROM stdin;
1	Action	\N
2	Adventure	\N
3	Animation	\N
4	Apocalyptic	\N
5	Biography	\N
6	Comedy	\N
7	Cosmic Horror	\N
8	Crime	\N
9	Dark Comedy	\N
10	Dark Fantasy	\N
11	Dinosaur	\N
12	Documentary	\N
13	Drama	\N
14	Dystopian	\N
15	Epic	\N
16	Fantasy	\N
17	Folk Drama	\N
18	Folk Horror	\N
19	Found Footage	\N
20	History	\N
21	Horror	\N
22	Martial Arts	\N
23	Medieval	\N
24	Monster Horror	\N
25	Music	\N
26	Musical	\N
27	Mystery	\N
28	Period Drama	\N
29	Politics	\N
30	Psychological Drama	\N
31	Romance	\N
32	Samurai	\N
33	Sci-Fi	\N
34	Slasher	\N
35	Sport	\N
36	Spy	\N
37	Superhero	\N
38	Suspense	\N
39	Thriller	\N
40	Tragedy	\N
41	Vampires	\N
42	War	\N
43	Western	\N
44	Zombie	\N
45	Zombie Drama	\N
46	\N	Action, Adventure
47	\N	Action, Adventure, Drama, Fantasy
48	\N	Action, Comedy
49	\N	Action, Crime
50	\N	Action, Crime, Politics, Dark Comedy, Drama
51	\N	Action, Drama
52	\N	Action, Fantasy
53	\N	Action, Martial Arts
54	\N	Action, Samurai
55	\N	Action, Sci-Fi
56	\N	Action, Spy
57	\N	Action, Superhero
58	\N	Action, Thriller
59	\N	Action, War
60	\N	Adventure, Drama
61	\N	Adventure, Drama, Horror, Mystery, Thriller
62	\N	Animation, Action, Drama, Sci-Fi
63	\N	Animation, Sci-Fi
64	\N	Apocalyptic, Zombie, Zombie Drama, Horror, Thriller, Dystopian
65	\N	Biography, Drama
66	\N	Biography, Drama, Sport
67	\N	Comedy, Crime
68	\N	Comedy, Drama
69	\N	Crime, Action
70	\N	Crime, Drama
71	\N	Crime, Drama, Mystery, Sci-Fi, Thriller
72	\N	Crime, Horror, Mystery
73	\N	Crime, Horror, Thriller
74	\N	Crime, Thriller
75	\N	Documentary, Biography
76	\N	Documentary, Drama
77	\N	Drama, Biography
78	\N	Drama, Biography, History
79	\N	Drama, Crime
80	\N	Drama, Fantasy
81	\N	Drama, Horror
82	\N	Drama, Horror, Sci-Fi, Thriller
83	\N	Drama, Horror, Sci-Fi, War
84	\N	Drama, Music
85	\N	Drama, Mystery
86	\N	Drama, Mystery, Thriller, Sci-Fi
87	\N	Drama, Romance
88	\N	Drama, Sport
89	\N	Drama, War
90	\N	Dystopian, Horror, Sci-Fi, Thriller
91	\N	Dystopian, Sci-Fi
92	\N	Epic, Fantasy, Dark Fantasy, Drama
93	\N	Epic, Fantasy, Dark Fantasy, Medieval
94	\N	Fantasy, Adventure
95	\N	Fantasy, Adventure, Dark Fantasy
96	\N	Fantasy, Drama, Horror, Mystery
97	\N	Fantasy, Horror
98	\N	Fantasy, Horror, Comedy
99	\N	Fantasy, Horror, Monster Horror, Cosmic Horror
100	\N	Fantasy, Martial Arts, Spy, Action, Adventure
101	\N	Fantasy, Sci-Fi
102	\N	Folk Horror, Horror, Thriller
103	\N	Found Footage, Horror
104	\N	Found Footage, Horror, Slasher
105	\N	Horror, Adventure, Found Footage
106	\N	Horror, Documentary
107	\N	Horror, Drama
108	\N	Horror, Drama, Found Footage
109	\N	Horror, Mystery
110	\N	Horror, Sci-Fi
111	\N	Horror, Sci-Fi, Found Footage
112	\N	Horror, Suspense
113	\N	Horror, Thriller
114	\N	Horror, Thriller, Cosmic Horror
115	\N	Horror, Thriller, Drama
116	\N	Horror, Thriller, Found Footage
117	\N	Horror, Thriller, Mystery, Suspense
118	\N	Horror, Thriller, Sci-Fi
119	\N	Horror, Thriller, Sci-Fi, Dystopian
120	\N	Horror, Thriller, Slasher
121	\N	Horror, Vampires, Slasher, Folk Drama, Period Drama
122	\N	Medieval, Dark Fantasy
123	\N	Musical, Romance
124	\N	Mystery, Horror, Thriller
125	\N	Mystery, Sci-Fi
126	\N	Mystery, Thriller
127	\N	Romance, Comedy
128	\N	Romance, Drama
129	\N	Sci-Fi, Action
130	\N	Sci-Fi, Action, Adventure
131	\N	Sci-Fi, Action, Slasher, Thriller
132	\N	Sci-Fi, Adventure, Action
133	\N	Sci-Fi, Adventure, Action, Dinosaur
134	\N	Sci-Fi, Adventure, Dinosaur
135	\N	Sci-Fi, Animation
136	\N	Sci-Fi, Crime
137	\N	Sci-Fi, Drama
138	\N	Sci-Fi, Drama, Crime
139	\N	Sci-Fi, Drama, Mystery, Adventure
140	\N	Sci-Fi, Horror
141	\N	Sci-Fi, Horror, Thriller, Slasher
142	\N	Sci-Fi, Romance
143	\N	Sci-Fi, Thriller, Slasher
144	\N	Vampires, Horror, Romance
145	\N	War, Drama
146	\N	War, Period Drama, Psychological Drama, Tragedy, Biography, Drama
147	\N	Western, Drama
\.


--
-- TOC entry 5070 (class 0 OID 16403)
-- Dependencies: 223
-- Data for Name: haswatched; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.haswatched (id, user_id, title_id, watch_date, watch_count, user_comment, user_rating, series_id) FROM stdin;
1	1	172	2025-12-01	1	Typical Sci Fi movie from 80s/90s it was worth watching	3.0	\N
2	1	173	2025-12-04	1	An average horror movie	3.0	\N
3	1	7563	2025-12-14	1	I am still preferring the 40s version	3.0	\N
4	1	7564	2025-12-17	1	Amazing, its perfect	5.0	\N
5	1	7565	2025-12-23	1	Not so good	3.0	\N
6	1	131	2025-12-23	3	Love it	4.0	\N
7	1	117	2024-01-01	1	Love it, but could have been better and I have forgotten the exact day I watched it	4.0	\N
8	1	116	2024-01-01	1	Love it	4.0	\N
9	1	134	2024-01-01	1	Love it	4.0	\N
10	1	226	2024-01-01	1	Must have watched lots of time, but never in english	5.0	\N
11	1	127	2024-01-01	1	Love it	4.0	\N
12	2	119	2025-12-28	1	Um clássico!	5.0	\N
13	2	6	2025-05-28	1	Muito bom, hostei	3.0	\N
14	2	203	2020-12-28	1	Não entendi nada	5.0	\N
15	5	42	2024-01-01	1	Muito legal	4.0	\N
16	5	13	2025-12-28	1	Muito bom	5.0	\N
17	3	8	2020-09-30	1	loved to see it in  the cinema	4.0	\N
18	3	46	2024-12-20	1	Very interesting	4.0	\N
19	4	4694	2025-12-28	1	One of the best movies of all time	5.0	\N
20	4	143	2025-12-28	1	Liked it very much	5.0	\N
21	1	\N	2025-12-25	1	<3	4.0	22
22	1	7567	2025-12-30	2	has some positive and negative points, its worth watching but not surpass the olders	3.0	\N
23	1	7566	2025-12-31	1	It was good to watch	4.0	\N
24	1	529	2025-12-29	1	Sci-fi combined with action, great movie	5.0	\N
25	1	227	2025-12-28	1	One of my favorites	5.0	\N
30	1	7569	2026-01-04	1	it was interesting, way better than alien 3	3.0	\N
31	1	7572	2026-01-03	1	The worst of the series	2.0	\N
32	1	7571	2026-01-02	1	Cool but following the same premise	4.0	\N
33	1	7566	2026-01-01	1	Cool	4.0	\N
34	1	238	2026-01-05	1	This movie is just perfect	5.0	\N
35	1	7591	2026-01-06	1	Although not as good as the first one, it starts a bit \\"Okay\\", but the film grows up and gives an amazing experience	4.0	\N
36	1	7592	2026-01-06	1	Not so good, but not so bad as it appears to be	3.0	\N
37	1	7593	2025-12-29	1	Méhhhhh	3.0	\N
38	1	7599	2026-01-08	1	Not to take to seriously	\N	\N
39	1	7600	2026-01-10	1	Interesting	\N	\N
40	1	7601	2026-01-11	1	The has a serious problem with brightness	\N	\N
41	1	7602	2026-01-12	1	Nothing special, just an adventure movie 	\N	\N
42	1	3747	2026-01-13	2	Too much action, interesting movie	\N	\N
43	1	4346	2026-01-15	1	Too much nudism (Im not complaining)	\N	\N
44	1	1	2026-01-17	1	One of my favorite generes and movie	10.0	\N
45	1	7598	2026-01-21	1	Too long	10.0	\N
46	1	7604	2026-01-23	1	Just another modern movie	6.0	\N
47	1	117	2026-01-23	2	Amazing	8.9	\N
48	1	7603	2026-01-18	1	Theres no comparison with the original one. Loved the practical effects	7.5	\N
49	1	4039	2026-01-30	2	One of my favorites	10.0	\N
50	1	7605	2026-01-29	1	An generic Sci-Fi Movie	6.0	\N
51	1	7580	2026-01-27	1	Cool, I would love to have a gun that explodes targets with a single bullet	7.5	\N
52	1	7606	2026-01-26	1	Too dark, old CGI	6.0	\N
53	1	\N	2025-12-20	2	Love it	9.5	12
54	1	7877	2026-01-31	1	A really nice experience	8.5	\N
55	1	7878	2026-02-04	1	Cool but, generic	6.5	\N
56	1	7884	2026-02-07	1	Interesting	8.0	\N
57	1	7885	2026-02-01	2	Cool	7.5	\N
58	1	7886	2026-02-06	2	the type of experience that you should only try once, it illustrates relationship between humans problems	7.0	\N
59	1	7889	2026-02-03	2	I like this film very mutch, it has some Blair Wich experience	8.5	\N
62	1	201	2026-02-10	2	Cool	9.0	\N
63	1	204	2026-02-11	2	Cool too	9.0	\N
64	1	7872	2026-02-15	2	Second time I watch, second time I sleep	6.0	\N
65	1	7873	2026-02-14	1	Stupid and 90% Soft porn	5.0	\N
66	1	7880	2026-02-12	2	Nice sequence	8.5	\N
67	1	7882	2026-02-09	2	Cool	7.8	\N
68	1	4012	2026-02-17	2	Seems like a remake of the first one, but gret	8.5	\N
70	1	129	2026-02-15	2	Mehh	7.0	\N
71	1	4325	2026-02-18	2	Shocking, amazing	9.0	\N
72	1	130	2026-02-20	2	Great Movie	8.0	\N
73	1	7887	2026-02-16	2	Nice movie	7.5	\N
74	1	7876	2026-02-24	2	not the best one but enjoyable	8.0	\N
75	1	7579	2026-03-02	1	really cool to watch	8.0	\N
76	1	7888	2026-02-28	1	mehh	6.0	\N
77	1	3818	2026-03-06	1	Beautiful movie, I loved it	9.5	\N
78	1	127	2026-03-10	2	Cool	8.0	\N
79	1	7893	2026-03-11	1	naaaaaaeeehhh	6.5	\N
80	1	4346	2026-03-01	2	Cool bro	7.5	\N
81	1	7883	2026-02-25	1	Too comic, do not take it so serious	7.0	\N
82	1	7881	2026-02-01	1	Very cool	8.0	\N
83	1	\N	2026-02-24	1	Soo few episodes, Im already missing it	8.9	24
69	1	7875	2026-02-20	2	Scary, funny, perfect	9.0	\N
94	1	226	2026-03-23	1	One of the best Sci Movies of all time	10.0	\N
95	1	5394	2026-03-18	2	Cool movie	8.5	\N
97	1	535	2026-03-22	1	Excellent sci-fi movie	9.0	\N
100	1	7894	2026-03-20	1	Long, confuse and goes anywhere	5.0	\N
101	1	19	2026-03-31	3	Its an amazing film but the sound is terrible	7.5	\N
102	1	20	2026-03-29	2	A must watch sci-fi	8.0	\N
103	1	7884	2026-03-28	2	this is a complement to the matrix movie	8.0	\N
104	1	7899	2026-03-24	2	One of the best Sci-Fi Action movies I have seen in my life	10.0	\N
105	1	7900	2026-03-27	1	Amazing althoug there were some unexplained things at the end	8.5	\N
\.


--
-- TOC entry 5072 (class 0 OID 16413)
-- Dependencies: 225
-- Data for Name: series; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.series (id, series_name, creator, year_release, genre_id) FROM stdin;
12	Alien: Earth	Noah Hawley	2025	141
13	True Detective	Nic Pizzolatto, Issa López	2014	8
14	The Outer Limits	Leslie Stevens	1995	33
15	The Simpsons	Matt Groening, James L. Brooks, Sam Simon	1989	3
16	The X Files	Chris Carter	1993	136
17	Millennium	Chris Carter	1996	136
18	Lost	J.J. Abrams, Jeffrey Lieber, Damon Lindelof	2004	139
19	The Walking Dead	Frank Darabont	2010	64
20	Breaking Bad	Vince Gilligan	2008	138
21	Game Of Thrones	David Benioff, D.B. Weiss	2011	92
22	Pluribus	Vince Gilligan	2025	91
23	It: Welcome to Derry	Jason Fuchs, Andy Muschietti, Barbara Muschietti	2025	113
24	A Knight of the Seven Kingdoms	George R.R. Martin, Ira Parker	2026	47
2	Black Mirror	Charlie Brooker	2011	33
\.


--
-- TOC entry 5074 (class 0 OID 16428)
-- Dependencies: 227
-- Data for Name: titles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.titles (id, name, director_id, year_release, category, runtime, genre_id) FROM stdin;
7881	I Am Joe Frazier	601	2025	Movie	2.05	66
7882	Soylent Green	180	1973	Movie	1.37	71
7883	The Warrior and the Sorceress	352	1984	Movie	1.21	101
7884	The Animatrix	602	2003	Movie	1.42	62
7885	The Black Cat	603	1934	Movie	1.05	72
7886	The Divide	604	2011	Movie	1.57	82
7887	The Evil Dead (Evil Dead I)	335	1981	Movie	1.25	21
7888	The Occupant	605	2025	Movie	1.40	86
7889	The Ritual	466	2017	Movie	1.34	61
7890	The Wolf Man	150	1941	Movie	1.10	81
7891	Threads	606	1984	Movie	1.50	83
7892	Vampyr	607	1932	Movie	1.13	97
4324	It	351	2017	Movie	0.00	124
1	Blair Witch	41	1999	Movie	0.00	19
2	The Pyramid	11	2014	Movie	0.00	105
3	The Sacrament	15	2013	Movie	0.00	108
4	The Incantation	18	2018	Movie	0.00	105
5	V/H/S: Beyond	16	2024	Movie	0.00	19
6	V/H/S: Halloween	17	2025	Movie	0.00	19
7	Enemy Mine	12	1985	Movie	0.00	33
8	Body Snatchers	13	1993	Movie	0.00	33
9	Lifeforce	14	1985	Movie	0.00	33
10	Batteries Not Included	83	1987	Movie	0.00	33
11	The Blob	84	1988	Movie	0.00	33
12	Flight of the Navigator 	85	1986	Movie	0.00	33
13	Starman	86	1984	Movie	0.00	33
14	The Ice Pirates	87	1984	Movie	0.00	33
15	Heavy Metal	19	1981	Animation	0.00	135
16	Heavy Metal 2	20	2000	Animation	0.00	135
17	Repo Men	88	1984	Movie	0.00	33
18	The Hidden	89	1987	Movie	0.00	33
19	Brazil	90	1985	Movie	0.00	33
20	The Fifth Element	91	1997	Movie	0.00	33
22	Dredd 2	93	2012	Movie	0.00	33
23	Solaris	94	2002	Movie	0.00	33
24	Fly Me To The Moon	95	2024	Movie	0.00	33
25	Ad Astra	96	2019	Movie	0.00	33
26	Equilibrium	97	2005	Movie	0.00	33
27	Kingdom Of The Planet Of The Apes	98	2024	Movie	0.00	33
28	Leave The World Behind	99	2023	Movie	0.00	33
29	Megalopolis	100	2024	Movie	0.00	33
30	The Day The Earth Stood Still	101	1951	Movie	0.00	33
31	The Thing From Another World	21	1951	Movie	0.00	33
32	The Thing	86	1982	Movie	0.00	33
33	The Fly I	102	1986	Movie	0.00	33
34	The Fly II	103	1989	Movie	0.00	33
35	Alienator	104	1990	Movie	0.00	33
36	Elevation	105	2024	Movie	0.00	33
37	Companion	106	2025	Movie	0.00	33
39	Frankenstein	108	2015	Movie	0.00	113
40	Midsommar	109	2019	Movie	0.00	113
41	In A Violent Nature	110	2024	Movie	0.00	113
42	MaXXXine	15	2024	Movie	0.00	113
43	The Watchers	111	2024	Movie	0.00	113
44	Bird Box	112	2018	Movie	0.00	118
45	The House Of The Devil	15	2009	Movie	0.00	113
46	Longlegss	113	2024	Movie	0.00	113
47	Apartment 7A	114	2024	Movie	0.00	113
48	The Substance	115	2024	Movie	0.00	113
49	Speak No Evil (Remake)	116	2024	Movie	0.00	113
50	Never Let Go	117	2024	Movie	0.00	113
51	Shutter	22	2004	Movie	0.00	113
52	Lights Out	118	2016	Movie	0.00	113
54	Antrum: The Deadliest Film Ever Made	23	2018	Movie	0.00	106
56	Frogman	121	2023	Movie	0.00	19
60	Invasion Of The Body Snatchers	123	1978	Movie	0.00	118
61	Speak No Evil	124	2022	Movie	0.00	113
62	Mad Max 1	125	1979	Movie	0.00	55
63	Ben-Hur	126	1959	Movie	0.00	46
64	Judge Dredd	127	1995	Movie	0.00	129
65	Vampires	86	1998	Movie	0.00	113
66	In The Mouth Of Madness	86	1994	Movie	0.00	114
67	Atrocious	128	2010	Movie	0.00	19
68	August Undergrounds Mordum	24	2003	Movie	0.00	104
69	Be My Cat	129	2015	Movie	0.00	19
70	The Taking Of Deborah Logan	130	2015	Movie	0.00	116
71	Diary of The Dead	131	2007	Movie	0.00	111
72	Grave Encounters	25	2011	Movie	0.00	103
73	The Houses October Built	132	2014	Movie	0.00	112
75	Host	133	2020	Movie	0.00	109
106	Daddys Head	134	2024	Movie	0.00	113
107	Carnage	135	1984	Movie	0.00	113
108	Cruising	136	1980	Movie	0.00	73
109	End of Days	137	1999	Movie	0.00	113
110	Blink Twice	138	2024	Movie	0.00	113
111	Y2K	139	2024	Movie	0.00	118
112	Frankenstein (1981)	140	1981	Movie	0.00	118
113	Dracula	26	1931	Movie	0.00	113
114	Freaks	594	1931	Movie	0.00	113
115	The Old Dark house	141	1931	Movie	0.00	113
117	Nosferatu	142	2024	Movie	0.00	113
118	The Omega Man	143	1971	Movie	0.00	119
119	Suspiria	144	1977	Movie	0.00	113
120	Suspiria (2018)	145	2018	Movie	0.00	113
121	Tusk	146	2014	Movie	0.00	113
122	Pulse	147	2001	Movie	0.00	113
123	Cure	147	1997	Movie	0.00	113
124	Heretic	27	2024	Movie	0.00	113
125	Smile 2	148	2024	Movie	0.00	113
126	Wolfman	149	2025	Movie	0.00	113
127	The Wolfman	150	1941	Movie	0.00	113
128	Final Destination: Bloodlines	151	2025	Movie	0.00	113
129	Dead of Night	28	1945	Movie	0.00	113
130	House of Wax	152	1953	Movie	0.00	113
131	I walked with a Zombie	153	1943	Movie	0.00	113
132	Jacob’s Ladder	154	1990	Movie	0.00	113
133	Lord of Illusions	155	1995	Movie	0.00	113
135	Eddington	109	2025	Movie	0.00	13
136	Bring Her Back	29	2025	Movie	0.00	113
137	28 Years Later	593	2025	Movie	0.00	113
138	Weapons	156	2025	Movie	0.00	113
139	The Conjuring: Last Rites	157	2025	Movie	0.00	113
140	Apocalypto	158	2006	Movie	0.00	113
141	Fear Below	159	2025	Movie	0.00	113
142	Venom: The Last Dance	160	2024	Movie	0.00	1
143	Gladiador II	161	2024	Movie	0.00	1
144	Falling Down	162	1993	Movie	0.00	1
145	The Eagle	163	2011	Movie	0.00	1
146	Kraven	164	2024	Movie	0.00	1
147	Armor	165	2024	Movie	0.00	1
149	Tenet	167	2020	Movie	0.00	1
150	Mission Impossible: The Final Reckoning	168	2024	Movie	0.00	1
151	Mystic River	169	2003	Movie	0.00	70
152	Red Lights	170	2012	Movie	0.00	70
153	The Alto Knights	171	2025	Movie	0.00	8
154	The Unholy Trinity	172	2025	Movie	0.00	8
155	Legend	161	1985	Movie	0.00	10
156	The Dark Crystal	30	1982	Movie	0.00	10
157	The Never Ending Story	12	1984	Movie	0.00	10
158	Melancholia	173	2011	Movie	0.00	13
159	The Crucible	174	1996	Movie	0.00	13
161	Slumdog Millionaire	31	2008	Movie	0.00	13
162	The Lord Of The Rings: The War Of Rohirrim	176	2024	Animation	0.00	93
163	The Lord Of The Rings	177	1978	Animation	0.00	93
164	Pandemic: The People, The Conspiracy, The Journey	178	2020	Documentary	0.00	76
165	Avicii: Im Tim	179	2024	Documentary	0.00	75
166	Conan: The Destroyer	180	1984	Movie	0.00	122
167	Conan: The Barbarian	181	1982	Movie	0.00	122
168	The Northman	142	2024	Movie	0.00	23
172	Time Cop	137	1994	Movie	0.00	136
173	Black Phone 2	92	2025	Movie	0.00	113
174	Dark City	185	1998	Movie	0.00	125
175	Ghost In The Shell	186	2017	Movie	0.00	55
201	Blade Runner 2049	187	2017	Movie	0.00	33
202	Taxi Driver	188	1976	Movie	0.00	79
203	2001: A Space Odyssey	189	1968	Movie	0.00	33
204	Blade Runner	161	1982	Movie	0.00	33
205	Lord Of The Rings: Fellowship of the Ring	190	2001	Movie	0.00	16
206	Drive	191	2011	Movie	0.00	70
207	Apocalypse Now	100	1979	Movie	0.00	145
208	There Will Be Blood	192	2007	Movie	0.00	13
210	The Good, The Bad and the Ugly	194	1966	Movie	0.00	43
211	Eyes Wide Shut	189	1999	Movie	0.00	85
212	The Dark Knight Rises	167	2012	Movie	0.00	1
213	No Country For Old Men	32	2007	Movie	0.00	74
214	Das Boot	12	1981	Movie	0.00	145
215	Goodfellas	188	1990	Movie	0.00	70
216	Lawrence Of Arabia	195	1962	Movie	0.00	60
217	Barry Lyndon	189	1975	Movie	0.00	13
218	The Godfather	100	1972	Movie	0.00	70
219	Pulp Fiction	196	1994	Movie	0.00	8
221	Terminator 2	198	1991	Movie	0.00	129
222	The Shining	189	1980	Movie	0.00	21
223	Gladiator	161	2000	Movie	0.00	51
224	For A Few Dollars More	194	1965	Movie	0.00	43
225	American Psycho	199	2000	Movie	0.00	39
226	The Matrix	33	1999	Movie	0.00	33
227	Alien	161	1979	Movie	0.00	140
228	Jurassic Park	200	1993	Movie	0.00	134
229	Stalker	201	1979	Movie	0.00	137
230	Star Wars - A New Hope	202	1977	Movie	0.00	33
232	Die Hard	204	1988	Movie	0.00	1
233	Star Wars - Revenge of the Sith	202	2005	Movie	0.00	33
234	La La Land	205	2016	Movie	0.00	123
235	The Dark Knight	167	2008	Movie	0.00	49
236	A Clockwork Orange	189	1971	Movie	0.00	136
237	Once Upon a Time in America	194	1984	Movie	0.00	70
238	Predator	204	1987	Movie	0.00	129
239	The Assassination Of Jesse James..	206	2007	Movie	0.00	147
240	Oldboy	207	2003	Movie	0.00	39
241	Lord of the Rings: Return of the King	190	2003	Movie	0.00	16
243	Seven Samurai	208	1954	Movie	0.00	60
244	Batman Vs Superman	209	2016	Movie	0.00	57
245	The End of Evangelion	210	1997	Animation	0.00	63
246	Blue Velvet	193	1986	Movie	0.00	126
247	The Big Lebowski	32	1998	Movie	0.00	6
248	Star Wars: Empire Strikes Back	211	1980	Movie	0.00	33
249	Black Panther	212	2018	Movie	0.00	57
327	The Godfather: Part II	100	1974	Movie	0.00	70
328	Eraserhead	193	1977	Movie	0.00	21
329	Casino	188	1995	Movie	0.00	70
330	Its A Wonderful Life	213	1946	Movie	0.00	80
331	Fight Club	214	1999	Movie	0.00	13
333	Harakiri	216	1962	Movie	0.00	13
334	Only God Forgives	191	2013	Movie	0.00	70
335	Nightcrawler	217	2014	Movie	0.00	39
336	Ikiru	208	1952	Movie	0.00	13
337	Problem Child 2	218	1991	Movie	0.00	6
338	Love Exposure	219	2008	Movie	0.00	13
339	Master and Commander	220	2003	Movie	0.00	60
340	12 Angry Men	221	1957	Movie	0.00	13
341	Persona	222	1966	Movie	0.00	13
342	Wild Strawberries	222	1957	Movie	0.00	13
343	Synecdoche, New York	223	2008	Movie	0.00	13
344	Memories of Murder	224	2003	Movie	0.00	74
345	One Flew Over the Cuckoos Nest	203	1975	Movie	0.00	13
346	The House That Jack Built	173	2018	Movie	0.00	107
347	The Tree of Life	225	2011	Movie	0.00	13
348	300	209	2006	Movie	0.00	1
349	Platoon	226	1986	Movie	0.00	145
350	Akira	227	1988	Animation	0.00	33
351	Whiplash	205	2014	Movie	0.00	13
353	Robocop	229	1987	Movie	0.00	129
354	Excalibur	230	1981	Movie	0.00	16
355	City of God	35	2002	Movie	0.00	70
356	Interstellar	167	2014	Movie	0.00	33
357	Under the Skin	231	2013	Movie	0.00	33
358	Come and See	232	1985	Movie	0.00	145
359	Lost in Translation	233	2003	Movie	0.00	87
362	The Shawshank Redemption	235	1994	Movie	0.00	13
363	The Silence of the Lambs	236	1991	Movie	0.00	39
529	Aliens	198	1986	Movie	0.00	33
530	Gattaca	237	1997	Movie	0.00	33
531	Forbidden Planet	238	1956	Movie	0.00	33
532	Primer	239	2004	Movie	0.00	33
533	Children of Men	240	2006	Movie	0.00	33
534	Dune	193	1984	Movie	0.00	33
536	District 9	242	2009	Movie	0.00	33
537	Europa Report	243	2013	Movie	0.00	33
538	Gravity	240	2013	Movie	0.00	33
540	Moon	244	2009	Movie	0.00	33
541	Ex Machina	245	2014	Movie	0.00	33
542	A.I.	200	2001	Movie	0.00	33
543	Minority Report	200	2002	Movie	0.00	33
544	Total Recall	229	1990	Movie	0.00	33
545	Avatar	198	2009	Movie	0.00	33
546	Silent Running	246	1972	Movie	0.00	33
547	12 Monkeys	90	1995	Movie	0.00	33
548	Escape from New York	86	1981	Movie	0.00	129
549	Star Trek: The Motion Picture	101	1979	Movie	0.00	33
550	Star Trek II: The Wrath of Khan	247	1982	Movie	0.00	33
551	Planet of the Apes	248	1968	Movie	0.00	33
552	Tron: Legacy	249	2010	Movie	0.00	33
553	Elysium	242	2013	Movie	0.00	33
554	The Martian	161	2015	Movie	0.00	33
555	The Terminator	198	1984	Movie	0.00	33
556	Terminator 2: Judgment Day	198	1991	Movie	0.00	33
557	Metropolis	250	1927	Movie	0.00	33
558	WALL-E	251	2008	Movie	0.00	33
559	Ghost in the Shell (1995)	252	1995	Animation	0.00	33
689	Her	253	2013	Movie	0.00	128
690	Kramer Vs. Kramer	254	1979	Movie	0.00	13
692	The Hunt	256	2012	Movie	0.00	13
693	Shame	257	2011	Movie	0.00	13
694	Under the Silver Lake	119	2018	Movie	0.00	126
695	Full Metal Jacket	189	1987	Movie	0.00	145
696	Demolition	258	2015	Movie	0.00	13
697	Be With You	259	2004	Movie	0.00	128
698	Sound of Metal	260	2019	Movie	0.00	13
699	O Cheiro do Ralo	261	2006	Movie	0.00	13
700	Le Samouraï	262	1967	Movie	0.00	74
701	Awakenings	263	1990	Movie	0.00	13
703	The Count of Monte Cristo	264	2002	Movie	0.00	2
704	The Deer Hunter	265	1978	Movie	0.00	89
705	The Truman Show	220	1998	Movie	0.00	13
706	The Bridge on the River Kwai	195	1957	Movie	0.00	145
707	The Killing Fields	266	1984	Movie	0.00	89
708	Palm Springs	267	2020	Movie	0.00	127
709	Rush	184	2013	Movie	0.00	88
710	The Passion of the Christ	158	2004	Movie	0.00	13
711	Green Street Hooligans	268	2005	Movie	0.00	79
712	Enemy	187	2013	Movie	0.00	39
714	The Searchers	270	1956	Movie	0.00	43
715	Rocky	271	1976	Movie	0.00	88
716	The Road	272	2009	Movie	0.00	13
717	The Graduate	273	1967	Movie	0.00	68
718	Warrior	274	2011	Movie	0.00	88
719	The Pianist	275	2002	Movie	0.00	89
720	Unbreakable	276	2000	Movie	0.00	39
721	Fargo	32	1996	Movie	0.00	70
722	Cloverfield	277	2008	Movie	0.00	39
724	Eurotrip	279	2004	Movie	0.00	6
725	The Wicker Man	280	1973	Movie	0.00	21
726	Manchester by the Sea	281	2016	Movie	0.00	13
727	Cast Away	282	2000	Movie	0.00	13
728	Vanilla Sky	283	2001	Movie	0.00	87
729	Into the Wild	284	2007	Movie	0.00	60
3696	Attack of the 50ft Woman	285	1958	Movie	0.00	33
3697	Robinson Crusoe on Mars	286	1964	Movie	0.00	33
3698	Seconds	287	1966	Movie	0.00	33
3699	The Face of Another	288	1966	Movie	0.00	33
3700	Barbarella	289	1968	Movie	0.00	33
3701	Je taime, Je taime	290	1968	Movie	0.00	33
3702	Westworld	291	1973	Movie	0.00	33
3703	Dark Star	86	1974	Movie	0.00	33
3704	Logans Run	292	1976	Movie	0.00	33
3706	Close Encounters of the Third Kind	200	1977	Movie	0.00	33
3707	Star Wars: A New Hope	202	1977	Movie	0.00	33
3708	Mad Max	125	1979	Movie	0.00	129
3709	Flash Gordon	294	1980	Movie	0.00	33
3710	Star Wars: The Empire Strikes Back	211	1980	Movie	0.00	33
3711	Outland	137	1981	Movie	0.00	33
3714	Videodrome	102	1983	Movie	0.00	33
3715	2010	137	1984	Movie	0.00	33
3716	Back to the Future	282	1985	Movie	0.00	33
3718	They Live	86	1988	Movie	0.00	129
3719	On the Silver Globe	296	1989	Movie	0.00	33
3720	Hardware	297	1990	Movie	0.00	33
3721	Stargate	298	1994	Movie	0.00	33
3722	Contact	282	1997	Movie	0.00	33
3723	eXistenZ	102	1999	Movie	0.00	33
3724	Galaxy Quest	299	1999	Movie	0.00	33
3726	Eternal Sunshine of the Spotless Mind	215	2004	Movie	0.00	128
3727	A Scanner Darkly	301	2006	Movie	0.00	33
3728	Paprika	302	2006	Animation	0.00	33
3729	Inception	167	2010	Movie	0.00	33
3730	Never Let Me Go	303	2010	Movie	0.00	137
3731	Looper	304	2012	Movie	0.00	33
3732	Spring	37	2014	Movie	0.00	142
3733	Edge of Tomorrow	305	2014	Movie	0.00	33
3734	Predestination	38	2014	Movie	0.00	33
3736	Arrival	187	2016	Movie	0.00	33
3737	Rogue One: A Star Wars Story	306	2016	Movie	0.00	33
3738	Okja	224	2017	Movie	0.00	33
3739	Annihilation	245	2018	Movie	0.00	33
3740	A Quiet Place	307	2018	Movie	0.00	140
3741	High Life	308	2018	Movie	0.00	33
3742	Prospect	39	2018	Movie	0.00	33
3743	The Vast of Night	309	2019	Movie	0.00	33
3744	Possessor	310	2020	Movie	0.00	33
3745	Sea Fever	311	2020	Movie	0.00	140
3746	Synchronic	37	2020	Movie	0.00	33
3747	Prey/Skull	312	2022	Movie	0.00	129
3818	The Night of the Hunter	314	1955	Movie	0.00	124
3819	House on Haunted Hill	141	1959	Movie	0.00	124
3820	Eyes Without a Face	315	1960	Movie	0.00	124
3821	Peeping Tom	316	1960	Movie	0.00	124
3822	Psycho	317	1960	Movie	0.00	124
3823	The Innocents	318	1961	Movie	0.00	124
3824	What Ever Happened to Baby Jane?	319	1962	Movie	0.00	124
3825	The Birds	317	1963	Movie	0.00	124
3826	The Haunting	101	1963	Movie	0.00	124
3827	Blood and Black Lace	595	1964	Movie	0.00	124
3828	Repulsion	275	1965	Movie	0.00	124
3829	Rosemarys Baby	275	1968	Movie	0.00	124
3831	Dont Look Now	293	1973	Movie	0.00	124
3832	The Exorcist	136	1973	Movie	0.00	124
3833	Black Christmas	320	1974	Movie	0.00	124
3834	The Texas Chain Saw Massacre	14	1974	Movie	0.00	124
3835	Jaws	200	1975	Movie	0.00	124
3836	The Omen	321	1976	Movie	0.00	124
3837	Carrie	322	1976	Movie	0.00	124
3995	Dawn of the Dead	131	1978	Movie	0.00	124
3996	Halloween	86	1978	Movie	0.00	124
3997	Phantasm	323	1979	Movie	0.00	124
3998	The Changeling	324	1980	Movie	0.00	124
3999	Friday the 13th	325	1980	Movie	0.00	124
4000	Possession	296	1981	Movie	0.00	124
4001	An American Werewolf in London	326	1981	Movie	0.00	124
4002	Creepshow	131	1982	Movie	0.00	124
4003	Basket Case	327	1982	Movie	0.00	124
4005	A Nightmare on Elm Street	328	1984	Movie	0.00	124
4006	Fright Night	329	1985	Movie	0.00	124
4007	The Return of the Living Dead	330	1985	Movie	0.00	124
4008	Demons	331	1985	Movie	0.00	124
4009	Re-Animator	332	1985	Movie	0.00	124
4010	The Hitcher	333	1986	Movie	0.00	124
4011	Henry: Portrait of a Serial Killer	334	1986	Movie	0.00	124
4012	Evil Dead II	335	1987	Movie	0.00	124
4013	The Lost Boys	162	1987	Movie	0.00	124
4039	Hellraiser	155	1987	Movie	0.00	124
4040	The Vanishing	336	1988	Movie	0.00	124
4041	Child Play	329	1988	Movie	0.00	124
4043	Jacobs Ladder	154	1990	Movie	0.00	124
4044	Misery	338	1990	Movie	0.00	124
4045	Braindead	190	1992	Movie	0.00	124
4046	Se7en	214	1995	Movie	0.00	124
4048	Ringu	339	1998	Movie	0.00	124
4049	The Blair Witch Project	41	1999	Movie	0.00	124
4050	The Sixth Sense	276	1999	Movie	0.00	124
4051	Audition	340	1999	Movie	0.00	124
4052	The Others	341	2001	Movie	0.00	124
4053	28 Days Later	593	2002	Movie	0.00	124
4054	Saw	342	2004	Movie	0.00	124
4056	The Descent	344	2005	Movie	0.00	124
4057	The Devils Rejects	345	2005	Movie	0.00	124
4058	Inside	42	2007	Movie	0.00	124
4059	Rec	43	2007	Movie	0.00	124
4060	Let the Right One In	346	2008	Movie	0.00	124
4061	Oculus	347	2013	Movie	0.00	124
4062	The Conjuring	342	2013	Movie	0.00	124
4320	Creep	348	2014	Movie	0.00	124
4321	The Babadook	349	2014	Movie	0.00	124
4322	The VVitch	142	2015	Movie	0.00	124
4323	Get Out	350	2017	Movie	0.00	124
4325	Hereditary	109	2018	Movie	0.00	124
4327	Je t’aime, Je t’aime	290	1968	Movie	0.00	124
4338	Conquest	352	1983	Movie	0.00	94
4339	The Beastmaster	323	1982	Movie	0.00	94
4340	Krull	353	1983	Movie	0.00	94
4341	Warrior Queen	354	2009	Movie	0.00	94
4342	Sorceress	355	1982	Movie	0.00	94
4343	Barbarian Queen	356	1985	Movie	0.00	94
4344	Hundra	357	1983	Movie	0.00	94
4345	Gor	358	1987	Movie	0.00	94
4346	Deathstalker	359	1983	Movie	0.00	94
4347	Red Sonja	180	1985	Movie	0.00	94
4348	Amazons	360	1986	Movie	0.00	94
4349	The Barbarians	361	1987	Movie	0.00	94
4350	Ladyhawke	321	1985	Movie	0.00	94
4351	Dragonslayer	83	1981	Movie	0.00	94
4352	Flesh + Blood	229	1985	Movie	0.00	10
4432	Road House	362	1989	Movie	0.00	1
4433	Unstoppable	363	2010	Movie	0.00	1
4434	Shaft	364	1971	Movie	0.00	1
4435	The Villainess	365	2017	Movie	0.00	1
4437	Die Hard 2	367	1990	Movie	0.00	1
4438	National Treasure	368	2004	Movie	0.00	1
4439	The Protector	369	2005	Movie	0.00	53
4440	Revenge	115	2017	Movie	0.00	1
4441	El Mariachi	370	1992	Movie	0.00	1
4442	A Touch of Zen	371	1971	Movie	0.00	53
4443	Top Gun	363	1986	Movie	0.00	1
4444	Con Air	372	1997	Movie	0.00	1
4445	The Expendables 2	372	2012	Movie	0.00	1
4446	The Mummy	373	1999	Movie	0.00	52
4448	Rush Hour	374	1998	Movie	0.00	1
4449	The Equalizer	375	2014	Movie	0.00	1
4450	Captain America: Civil War	44	2016	Movie	0.00	57
4451	Air Force One	12	1997	Movie	0.00	1
4452	Bloodsport	376	1988	Movie	0.00	53
4453	Blade	377	1998	Movie	0.00	52
4454	Bad Boys	378	1995	Movie	0.00	1
4455	Die Hard With a Vengeance	204	1995	Movie	0.00	1
4456	The Running Man	379	1987	Movie	0.00	55
4457	Code of Silence	380	1985	Movie	0.00	1
4458	Shoot Em Up	381	2007	Movie	0.00	1
4459	Crank	45	2006	Movie	0.00	1
4461	Batman	382	1989	Movie	0.00	57
4462	Under Siege	380	1992	Movie	0.00	1
4463	Independence Day	298	1996	Movie	0.00	55
4464	Bullitt	353	1968	Movie	0.00	1
4465	Wanted	383	2008	Movie	0.00	1
4466	Superman: The Movie	321	1978	Movie	0.00	57
4467	Ronin	287	1998	Movie	0.00	58
4468	Cliffhanger	367	1993	Movie	0.00	1
4668	Hot Fuzz	343	2007	Movie	0.00	48
4669	The Warriors	385	1979	Movie	0.00	1
4670	Starship Troopers	229	1997	Movie	0.00	55
4671	Elite Squad 2	255	2010	Movie	0.00	1
4672	Point Break	386	1991	Movie	0.00	1
4673	The Long Kiss Goodnight	367	1996	Movie	0.00	1
4674	The Guest	166	2014	Movie	0.00	58
4675	Taken	387	2008	Movie	0.00	1
4676	True Lies	198	1994	Movie	0.00	1
4677	Demolition Man	388	1993	Movie	0.00	55
4678	Hardcore Henry	389	2015	Movie	0.00	1
4680	Brotherhood of the Wolf	391	2001	Movie	0.00	52
4681	Kingsman: The Secret Service	392	2014	Movie	0.00	1
4682	Big Trouble in Little China	86	1986	Movie	0.00	52
4683	Atomic Blonde	393	2017	Movie	0.00	1
4684	Rumble in the Bronx	394	1995	Movie	0.00	53
4685	District B13	387	2004	Movie	0.00	1
4686	Beverly Hills Cop	395	1984	Movie	0.00	1
4688	Collateral	197	2004	Movie	0.00	58
4689	Iron Monkey	396	1993	Movie	0.00	53
4690	Battle Royale	397	2000	Movie	0.00	1
4691	Spider-Man 2	335	2004	Movie	0.00	57
4692	13 Assassins	340	2010	Movie	0.00	54
4693	Full Contact	398	1992	Movie	0.00	1
4694	Indiana Jones and the Last Crusade	200	1989	Movie	0.00	46
4695	Kung Fu Hustle	399	2004	Movie	0.00	48
4696	A Better Tomorrow	400	1986	Movie	0.00	1
4697	Iron Man	401	2008	Movie	0.00	57
4698	The Night Comes for Us	402	2018	Movie	0.00	1
4699	Logan	403	2017	Movie	0.00	51
4700	Goldfinger	404	1964	Movie	0.00	56
4702	Wonder Woman	405	2017	Movie	0.00	57
4703	The Chinese Connection	406	1972	Movie	0.00	53
4704	Captain America: The Winter Soldier	44	2014	Movie	0.00	57
5120	The French Connection	136	1971	Movie	0.00	49
5121	Furious 7	342	2015	Movie	0.00	1
5122	La Femme Nikita	91	1990	Movie	0.00	58
5123	Supercop	394	1992	Movie	0.00	53
5124	Dirty Harry	407	1971	Movie	0.00	49
5125	X2	408	2003	Movie	0.00	57
5126	The Fugitive	380	1993	Movie	0.00	58
5127	Braveheart	158	1995	Movie	0.00	59
5129	Dredd	93	2012	Movie	0.00	55
5130	The Bourne Identity	305	2002	Movie	0.00	58
5131	Ip Man	409	2008	Movie	0.00	53
5132	Face/Off	400	1997	Movie	0.00	1
5133	To Live and Die in L.A.	136	1985	Movie	0.00	49
5134	Mission: Impossible - Ghost Protocol	410	2011	Movie	0.00	1
5135	Fast Five	411	2011	Movie	0.00	1
5136	Lethal Weapon	321	1987	Movie	0.00	1
5137	The Rock	378	1996	Movie	0.00	1
5138	John Wick: Chapter 2	412	2017	Movie	0.00	1
5139	Casino Royale	413	2006	Movie	0.00	56
5140	Baby Driver	343	2017	Movie	0.00	1
5142	The Killer	400	1989	Movie	0.00	1
5143	The Raid 2	415	2014	Movie	0.00	53
5144	Enter the Dragon	416	1973	Movie	0.00	53
5145	Commando	417	1985	Movie	0.00	1
5146	First Blood	418	1982	Movie	0.00	1
5147	Mission: Impossible - Rogue Nation	168	2015	Movie	0.00	1
5148	Kill Bill: Vol. 1	196	2003	Movie	0.00	1
5149	The Professional	91	1994	Movie	0.00	58
5150	Speed	419	1994	Movie	0.00	1
5151	Drunken Master II	420	1994	Movie	0.00	53
5152	John Wick	412	2014	Movie	0.00	1
5153	Crouching Tiger, Hidden Dragon	421	2000	Movie	0.00	52
5154	The Bourne Ultimatum	422	2007	Movie	0.00	1
5235	The Raid: Redemption	415	2011	Movie	0.00	53
5236	Mission: Impossible - Fallout	168	2018	Movie	0.00	1
5237	Raiders of the Lost Ark	200	1981	Movie	0.00	46
5238	Hard-Boiled	400	1992	Movie	0.00	1
5393	1408	423	2007	Movie	0.00	124
5394	The Crazies	424	2010	Movie	0.00	124
5395	Eraser	84	1996	Movie	0.00	58
5396	Triangle	425	2009	Movie	0.00	124
5397	Cube	426	1997	Movie	0.00	124
5398	Trick or Treat	427	1986	Movie	0.00	124
5399	Isolation	428	2005	Movie	0.00	124
5400	The Objective	8	2008	Movie	0.00	124
5402	Lake Mungo	430	2008	Movie	0.00	124
5403	Day of the Dead	131	1985	Movie	0.00	124
5404	Dead or Alive	340	1999	Movie	0.00	58
5405	Drag Me to Hell	335	2009	Movie	0.00	124
5406	The Last House on the Left	328	1972	Movie	0.00	124
5407	Open Water	431	2003	Movie	0.00	124
5408	Dead Ringers	102	1988	Movie	0.00	124
5409	The Fly	102	1986	Movie	0.00	140
5410	May	432	2002	Movie	0.00	124
3830	Night of the Living Dead	131	1968	Movie	0.00	124
6338	Fragile	433	2005	Movie	0.00	124
6340	Paranormal Activity	435	2007	Movie	0.00	124
6341	Teeth	436	2007	Movie	0.00	124
6342	The Mist	235	2007	Movie	0.00	124
6343	Pontypool	437	2008	Movie	0.00	124
6344	The Brood	102	1979	Movie	0.00	124
6345	Dog Soldiers	344	2002	Movie	0.00	124
6346	Ginger Snaps	438	2000	Movie	0.00	124
6347	Eden Lake	116	2008	Movie	0.00	124
6348	Near Dark	386	1987	Movie	0.00	124
7317	Trick Em Treat	439	2007	Movie	0.00	124
7318	The Devil’s Rejects	345	2005	Movie	0.00	124
7319	Eeden Lake	116	2008	Movie	0.00	124
7526	Creature from the Black Lagoon	596	1954	Movie	0.00	33
7527	Destination Moon	440	1950	Movie	0.00	33
7528	Donovans Brain	441	1953	Movie	0.00	33
7529	Half Human	442	1955	Movie	0.00	33
7530	I Married a Monster from Outer Space	443	1958	Movie	0.00	33
7531	I Was a Teenage Werewolf	444	1957	Movie	0.00	33
7532	Invaders from Mars	445	1953	Movie	0.00	33
7533	Island of Terror	446	1966	Movie	0.00	33
7534	It! The Terror from Beyond Space	447	1958	Movie	0.00	33
7535	Journey to the Center of the Earth	448	1959	Movie	0.00	33
7536	Night of the Demon	153	1957	Movie	0.00	33
7537	On the Beach	449	1959	Movie	0.00	33
7538	Plan 9 from Outer Space	450	1959	Movie	0.00	33
7539	Planet of the Vampires	595	1965	Movie	0.00	33
7540	Red Planet Mars	451	1952	Movie	0.00	33
7542	Tarantula	596	1955	Movie	0.00	33
7543	The Beast from 20,000 Fathoms	453	1953	Movie	0.00	33
7544	The Black Scorpion	49	1957	Movie	0.00	33
7545	The Brain That Wouldnt Die	454	1962	Movie	0.00	33
7546	The Day of the Triffids	50	1962	Movie	0.00	33
7547	The Day the Earth Caught Fire	455	1961	Movie	0.00	33
7548	The H-Man	82	1958	Movie	0.00	33
7549	The Human Vapor	82	1960	Movie	0.00	33
7551	The Last Man on Earth	51	1964	Movie	0.00	33
7552	The Man From Planet X	456	1951	Movie	0.00	33
7553	The Mole People	457	1956	Movie	0.00	33
7554	The Secret of the Telegian	458	1960	Movie	0.00	33
7555	The Time Machine	459	1960	Movie	0.00	33
7556	The War of the Worlds	286	1953	Movie	0.00	33
7557	The World, the Flesh and the Devil	460	1959	Movie	0.00	33
7558	Them!	461	1954	Movie	0.00	33
7559	This Island Earth	52	1955	Movie	0.00	33
7560	Village of the Damned	462	1960	Movie	0.00	33
7561	When Worlds Collide	463	1951	Movie	0.00	33
7563	Frankenstein (2025)	465	2025	Movie	0.00	113
7564	Predator: Badlands	312	2025	Movie	0.00	129
7565	Dracula: A Love Tale	91	2025	Movie	0.00	144
7566	Alien: Prometheus	161	2012	Movie	0.00	143
7567	Hellraiser (2022)	466	2022	Movie	0.00	120
7569	Alien: Ressurection	467	1997	Movie	0.00	143
7570	Alien: Covenant	161	2017	Movie	0.00	143
7571	Alien: Romulus	468	2024	Movie	0.00	143
7572	Alien³	214	1992	Movie	0.00	143
7580	Sleepwalkers	470	1992	Movie	1.29	99
7591	Predator II	472	1997	Movie	0.00	131
7592	Predators (Predator III)	473	2010	Movie	0.00	131
7593	Sinners	212	2025	Movie	0.00	121
7598	Aliens Expanded	474	2024	Documentary	0.00	12
7599	The Predator	475	2018	Movie	0.00	130
691	Tropa de Elite	255	2007	Movie	0.00	70
7880	Hellbound: Hellraiser II	155	1988	Movie	1.37	21
21	The Day The Earth Stood Still (Remake)	92	2008	Movie	0.00	33
38	The Dark And The Wicked	107	2020	Movie	0.00	113
53	It Follows	119	2015	Movie	0.00	117
55	As Above So Below	120	2015	Movie	0.00	19
59	Megan Is Missing	122	2011	Movie	0.00	19
74	The Poughkeepsie Tapes	120	2007	Movie	0.00	109
116	The Bride Of Frankenstein	140	1935	Movie	0.00	113
134	The Invisible man	140	1933	Movie	0.00	113
148	Godzilla X Kong: The New Empire	166	2024	Movie	0.00	1
160	A Different Man	175	2024	Movie	0.00	13
169	The Sword And The Sorcerer	182	1982	Movie	0.00	122
170	Waterloo	183	1970	Movie	0.00	42
171	Cinderela Man	184	2005	Movie	0.00	65
209	Mulholland Drive	193	2001	Movie	0.00	126
220	Heat	197	1995	Movie	0.00	69
231	Amadeus	203	1984	Movie	0.00	77
242	Lord of the Rings: The Two Towers	190	2002	Movie	0.00	16
332	Eternal Sunshine of a Spotless Mind	215	2004	Movie	0.00	128
352	In Bruges	228	2008	Movie	0.00	67
360	Mirror	201	1975	Movie	0.00	13
361	Chungking Express	234	1994	Movie	0.00	87
535	Event Horizon	241	1997	Movie	0.00	140
539	Sunshine	593	2007	Movie	0.00	33
702	Call Me By Your Name	145	2017	Movie	0.00	128
713	Saturday Night Fever	269	1977	Movie	0.00	84
723	Trois Couleurs: Blanc	278	1994	Movie	0.00	13
3705	The Man Who Fell to Earth	293	1976	Movie	0.00	33
3712	E.T.	200	1982	Movie	0.00	33
3713	Tron	295	1982	Movie	0.00	33
3725	Donnie Darko	300	2001	Movie	0.00	33
3735	Mad Max: Fury Road	125	2015	Movie	0.00	129
3817	Les Diaboliques	313	1955	Movie	0.00	124
7601	Alien vs Predator: Requiem	53	2007	Movie	0.00	132
7602	Jurassic World: Rebirth	306	2025	Movie	0.00	133
7603	Deathstalker (2025)	477	2025	Movie	0.00	95
7604	One Batle After Another	192	2025	Movie	0.00	50
7605	Oblivion	249	2013	Movie	2.40	33
7606	The Relic	137	1997	Movie	1.50	141
7872	Cat People	153	1942	Movie	1.13	102
7874	Day of Night	28	1945	Movie	1.45	96
7875	Evil Dead III (Army of Darkness)	335	1992	Movie	1.21	98
7876	Evil Dead IV	468	2013	Movie	1.31	21
7877	Evil Dead: Rise (Evil Dead V)	599	2023	Movie	1.37	21
7878	F1 The Movie	600	2025	Movie	2.10	51
7879	Godzilla	82	1954	Movie	1.36	110
7893	28 Years Later: The Bone Temple	1	2026	Movie	1.49	90
7894	Return To Silent Hill	391	2026	Movie	1.46	115
4004	Poltergeist	14	1982	Movie	0.00	124
4042	Pet Sematary	337	1989	Movie	0.00	124
4047	Scream	328	1996	Movie	0.00	124
4055	Shaun of the Dead	343	2004	Movie	0.00	124
4326	Attack of the 50 Foot Woman	285	1958	Movie	0.00	124
4436	Highlander	366	1986	Movie	0.00	52
4447	Mr. & Mrs. Smith	305	2005	Movie	0.00	1
4460	Machete	370	2010	Movie	0.00	1
4469	The Avengers	384	2012	Movie	0.00	57
4679	Police Story	390	1985	Movie	0.00	53
4687	Ong-Bak: The Thai Warrior	369	2003	Movie	0.00	53
4701	Assault on Precinct 13	86	1976	Movie	0.00	1
5128	Avengers: Endgame	44	2019	Movie	0.00	57
5141	Fist of Legend	414	1994	Movie	0.00	53
5155	Mad Max 2: The Road Warrior	125	1981	Movie	0.00	1
5401	Session 9	429	2001	Movie	0.00	124
6337	Room 1408	423	2007	Movie	0.00	124
6339	Miracle Mile	434	1988	Movie	0.00	124
7525	Caltiki: The Immortal Monster	48	1959	Movie	0.00	33
7541	Robot Monster	452	1953	Movie	0.00	33
7550	The Incredible Shrinking Man	596	1957	Movie	0.00	33
7562	X: The Man with the X-Ray Eyes	464	1963	Movie	0.00	33
7579	Pirates Of Silicon Valley	469	1999	Movie	1.35	78
7581	The Imitation Game	471	2014	Movie	0.00	146
7600	Alien vs Predator	476	2004	Movie	0.00	132
7873	Day of the warrior	598	1996	Movie	1.36	100
7898	Matrix: Reloaded	33	2003	Movie	2.18	130
7899	The Matrix: Reloaded	33	2003	Movie	2.18	55
7900	The Matrix: Revolutions	33	2003	Movie	2.09	55
\.


--
-- TOC entry 5076 (class 0 OID 16441)
-- Dependencies: 229
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, user_name, email) FROM stdin;
1	Vin Martins	vinmartins@localcinema.com
2	Peewee Brothers	peeweebrothers@localcinema.com
3	João Da Silva	joaodasilva@localcinema.com
4	Maria Da Silva	mariadasilva@localcinema.com
5	Lucas do Refúgio cult	lucasdorefugiocult@localcinema.com
\.


--
-- TOC entry 5078 (class 0 OID 16450)
-- Dependencies: 231
-- Data for Name: watchlist; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.watchlist (id, title_id) FROM stdin;
66	116
70	226
75	7559
69	7581
23	7879
77	7892
\.


--
-- TOC entry 5085 (class 0 OID 0)
-- Dependencies: 220
-- Name: directors_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.directors_id_seq', 26, true);


--
-- TOC entry 5086 (class 0 OID 0)
-- Dependencies: 222
-- Name: genres_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.genres_id_seq', 147, true);


--
-- TOC entry 5087 (class 0 OID 0)
-- Dependencies: 224
-- Name: haswatched_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.haswatched_id_seq', 105, true);


--
-- TOC entry 5088 (class 0 OID 0)
-- Dependencies: 226
-- Name: series_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.series_id_seq', 2, true);


--
-- TOC entry 5089 (class 0 OID 0)
-- Dependencies: 228
-- Name: titles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.titles_id_seq', 7900, true);


--
-- TOC entry 5090 (class 0 OID 0)
-- Dependencies: 230
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- TOC entry 5091 (class 0 OID 0)
-- Dependencies: 232
-- Name: watchlist_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.watchlist_id_seq', 1, false);


--
-- TOC entry 4891 (class 2606 OID 16456)
-- Name: directors directors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.directors
    ADD CONSTRAINT directors_pkey PRIMARY KEY (id);


--
-- TOC entry 4893 (class 2606 OID 16458)
-- Name: genres genres_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.genres
    ADD CONSTRAINT genres_pkey PRIMARY KEY (id);


--
-- TOC entry 4895 (class 2606 OID 16460)
-- Name: haswatched haswatched_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.haswatched
    ADD CONSTRAINT haswatched_pkey PRIMARY KEY (id);


--
-- TOC entry 4897 (class 2606 OID 16462)
-- Name: series series_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.series
    ADD CONSTRAINT series_pkey PRIMARY KEY (id);


--
-- TOC entry 4899 (class 2606 OID 16464)
-- Name: series series_series_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.series
    ADD CONSTRAINT series_series_name_key UNIQUE (series_name);


--
-- TOC entry 4901 (class 2606 OID 16466)
-- Name: titles titles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.titles
    ADD CONSTRAINT titles_pkey PRIMARY KEY (id);


--
-- TOC entry 4903 (class 2606 OID 16468)
-- Name: titles titles_title_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.titles
    ADD CONSTRAINT titles_title_key UNIQUE (name);


--
-- TOC entry 4905 (class 2606 OID 16470)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 4907 (class 2606 OID 16472)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4909 (class 2606 OID 16474)
-- Name: users users_user_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_user_name_key UNIQUE (user_name);


--
-- TOC entry 4911 (class 2606 OID 16476)
-- Name: watchlist watchlist_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.watchlist
    ADD CONSTRAINT watchlist_pkey PRIMARY KEY (id);


--
-- TOC entry 4912 (class 2606 OID 16477)
-- Name: haswatched haswatched_series_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.haswatched
    ADD CONSTRAINT haswatched_series_id_fkey FOREIGN KEY (series_id) REFERENCES public.series(id);


--
-- TOC entry 4913 (class 2606 OID 16482)
-- Name: haswatched haswatched_title_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.haswatched
    ADD CONSTRAINT haswatched_title_id_fkey FOREIGN KEY (title_id) REFERENCES public.titles(id);


--
-- TOC entry 4914 (class 2606 OID 16487)
-- Name: haswatched haswatched_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.haswatched
    ADD CONSTRAINT haswatched_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4915 (class 2606 OID 16492)
-- Name: series series_genre_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.series
    ADD CONSTRAINT series_genre_id_fkey FOREIGN KEY (genre_id) REFERENCES public.genres(id);


--
-- TOC entry 4916 (class 2606 OID 16497)
-- Name: titles titles_director_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.titles
    ADD CONSTRAINT titles_director_id_fkey FOREIGN KEY (director_id) REFERENCES public.directors(id);


--
-- TOC entry 4917 (class 2606 OID 16502)
-- Name: titles titles_genre_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.titles
    ADD CONSTRAINT titles_genre_id_fkey FOREIGN KEY (genre_id) REFERENCES public.genres(id);


--
-- TOC entry 4918 (class 2606 OID 16507)
-- Name: watchlist watchlist_title_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.watchlist
    ADD CONSTRAINT watchlist_title_id_fkey FOREIGN KEY (title_id) REFERENCES public.titles(id);


-- Completed on 2026-04-02 10:54:58

--
-- PostgreSQL database dump complete
--

\unrestrict J1jIw9u4JITzJ0Qdb1r4htoDK4QEyeE45nqy17hBMX1AkeoQKGAQUZGKiG63958

